/**
 * GroupMock.jsx — Ranklify v10
 * Full lobby → ready system → synchronized exam → quit detection
 * → ranked group results → downloadable PDF
 */
import { useState, useEffect, useRef } from "react";
import { QUESTION_BANK } from "../data/subjects";
import { useApp } from "../context/AppContext";

/* ─── seeded shuffle ───────────────────────────────────────── */
function seededShuffle(arr, seed) {
  const a = [...arr]; let s = (seed % 2147483647) || 1;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 16807) % 2147483647;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
function buildPaper(seed) {
  const base = seededShuffle([...QUESTION_BANK], seed);
  let pool = [...base];
  while (pool.length < 100) pool = [...pool, ...base];
  return pool.slice(0, 100);
}
const fmt = s => `${String(Math.floor(s / 60)).padStart(2,"0")}:${String(s % 60).padStart(2,"0")}`;
const TOTAL_SECS = 120 * 60;

/* ─── PDF download (no preview window) ───────────────────── */
function downloadGroupPDF(group, users, me, mockNum) {
  const ranked = group.members
    .filter(id => !group.quit?.[id])
    .map(id => {
      const u = id === me.id ? me : (users.find(x => x.id === id) || { name:"Unknown", profile:{} });
      const r = group.results[id] || {};
      return { name:u.name, branch:u.profile?.branch||"—", score:r.score||0, correct:r.correct||0, wrong:r.wrong||0, accuracy:r.accuracy||0, time:r.timeTaken||0 };
    })
    .sort((a,b) => b.score - a.score);

  const medals = ["🥇","🥈","🥉","💔"];
  const rankLabels = ["1st","2nd","3rd","Loser"];

  const html = `<!DOCTYPE html><html><head><title>ranklify.mocktest${mockNum}</title>
<style>body{font-family:Arial;padding:28px;color:#222;max-width:860px;margin:0 auto}
h1{color:#4f8ef7;font-size:20px;margin:4px 0}
.sub{color:#888;font-size:11px}
table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
th{background:linear-gradient(135deg,#4f8ef7,#a855f7);color:#fff;padding:10px 13px;text-align:left}
td{padding:9px 13px;border-bottom:1px solid #eee}
tr:nth-child(even)td{background:#f9f9f9}
.gold td{background:rgba(251,191,36,0.1)!important}
.loser td{background:rgba(239,68,68,0.05)!important}
.foot{margin-top:24px;color:#aaa;font-size:10px;text-align:center}
</style></head><body>
<div style="font-size:22px;font-weight:900;color:#4f8ef7">⚡ Ranklify</div>
<p class="sub">DDCET Group Mock Test · ${new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})}</p>
<h1>Group Mock Results — ${ranked.length} Players</h1>
<p style="background:#f0fdf4;color:#166534;padding:10px;border-radius:6px;font-size:13px;margin-top:10px">
  🏆 Winner: <b>${ranked[0]?.name}</b> — ${ranked[0]?.score} marks (${ranked[0]?.accuracy}% accuracy)</p>
<table><thead><tr><th>Rank</th><th>Name</th><th>Score /200</th><th>Correct</th><th>Wrong</th><th>Accuracy</th><th>Time</th></tr></thead>
<tbody>${ranked.map((m,i)=>`<tr class="${i===0?"gold":i===ranked.length-1?"loser":""}">
  <td><b>${rankLabels[i]||"#"+(i+1)} ${medals[i]||""}</b></td>
  <td><b>${m.name}</b><br><span style="font-size:10px;color:#888">${m.branch}</span></td>
  <td style="color:#4f8ef7;font-weight:800">${m.score}</td>
  <td style="color:#16a34a">${m.correct}</td><td style="color:#dc2626">${m.wrong}</td>
  <td>${m.accuracy}%</td>
  <td>${Math.floor(m.time/60)}m${m.time%60}s</td>
</tr>`).join("")}</tbody></table>
${group.quit&&Object.keys(group.quit).length>0?`<p style="font-size:12px;color:#dc2626;margin-top:12px">⚠️ ${Object.keys(group.quit).map(id=>{ const u=users.find(x=>x.id===id); return u?.name||"Unknown"; }).join(", ")} quit the exam early and are not ranked.</p>`:""}
<p class="foot">Generated by Ranklify · File: ranklify.mocktest${mockNum}.pdf</p>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = `ranklify.mocktest${mockNum}.pdf`; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/* ═══════════════════════════════════════════════════════════════ */
export default function GroupMock() {
  const {
    user, users, darkMode, groups, invites,
    myConnections, createGroup, sendGroupInvite,
    acceptGroupInvite, rejectGroupInvite,
    setReady, startGroupSession, submitGroupResult, quitGroup,
    myGroupInvites, addResult, myResults,
  } = useApp();

  const T      = darkMode;
  const txt    = T ? "#e2e2f0" : "#111";
  const sub    = T ? "#555"    : "#888";
  const cardBg = T ? "rgba(255,255,255,0.03)" : "#fff";
  const cardBr = T ? "rgba(255,255,255,0.07)" : "#e5e7eb";

  const Btn = (v="primary") => ({
    padding:"10px 22px", borderRadius:9, border:"none", cursor:"pointer",
    fontSize:13, fontWeight:700, fontFamily:"inherit",
    background: v==="primary" ? "linear-gradient(135deg,#4f8ef7,#a855f7)"
              : v==="green"   ? "linear-gradient(135deg,#4ade80,#22c55e)"
              : v==="danger"  ? "rgba(239,68,68,0.15)"
              : T ? "rgba(255,255,255,0.07)" : "#f3f4f6",
    color: (v==="primary"||v==="green") ? "#fff" : v==="danger" ? "#f87171" : txt,
  });

  const [phase,     setPhase]     = useState("lobby");
  const [questions, setQuestions] = useState([]);
  const [answers,   setAnswers]   = useState({});
  const [curr,      setCurr]      = useState(0);
  const [timeLeft,  setTimeLeft]  = useState(TOTAL_SECS);
  const [startedAt, setStartedAt] = useState(null);
  const [myResult,  setMyResult]  = useState(null);
  const [loserData, setLoserData] = useState(null);
  const [quitNotifs, setQuitNotifs] = useState([]); // [{name, ts}]
  const timerRef    = useRef(null);
  const prevQuitRef = useRef({});

  /* my active group (non-done session I'm in and haven't quit) */
  const myGroup = groups.find(g =>
    g.members.includes(user?.id) &&
    g.status !== "done" &&
    !g.quit?.[user?.id]
  ) || null;

  const pendingInvites = myGroupInvites ? myGroupInvites() : [];
  const connections    = myConnections  ? myConnections()  : [];

  /* next mock number for this user */
  const nextMockNum = (myResults?.filter(r=>r.isMock)?.length || 0) + 1;

  /* ── watch group status + quit notifications ── */
  useEffect(() => {
    if (!myGroup) return;

    /* detect new quitters and show notification */
    const currentQuit = myGroup.quit || {};
    Object.keys(currentQuit).forEach(qId => {
      if (!prevQuitRef.current[qId] && qId !== user.id) {
        const qu = users.find(u => u.id === qId);
        const name = qu?.name || "A student";
        setQuitNotifs(n => [...n, { name, ts: Date.now() }]);
        setTimeout(() => setQuitNotifs(n => n.filter(x => x.ts !== Date.now())), 5000);
      }
    });
    prevQuitRef.current = currentQuit;

    /* transition: lobby → running */
    if (myGroup.status === "running" && phase === "lobby") {
      const qs = buildPaper(myGroup.seed);
      setQuestions(qs); setAnswers({}); setCurr(0);
      setTimeLeft(TOTAL_SECS); setStartedAt(Date.now());
      setPhase("running");
    }

    /* transition: running/waiting → done */
    if (myGroup.status === "done" && (phase==="running"||phase==="waiting")) {
      setPhase("done");
      const activeMembers = myGroup.members.filter(id => !myGroup.quit?.[id]);
      const ranked = activeMembers
        .map(id => ({ id, score: myGroup.results[id]?.score || 0 }))
        .sort((a,b) => b.score - a.score);
      const loserId = ranked[ranked.length - 1]?.id;
      const loserU  = loserId === user.id ? user : users.find(u => u.id === loserId);
      setLoserData({ name: loserU?.name || "Unknown", isMe: loserId === user.id });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [myGroup?.status, JSON.stringify(myGroup?.quit), myGroup?.members?.length]);

  /* ── timer ── */
  useEffect(() => {
    if (phase !== "running") return;
    timerRef.current = setInterval(() => {
      setTimeLeft(t => { if(t<=1){clearInterval(timerRef.current);doSubmit();return 0;} return t-1; });
    }, 1000);
    return () => clearInterval(timerRef.current);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase]);

  /* ── submit ── */
  async function doSubmit() {
    clearInterval(timerRef.current);
    const elapsed = Math.round((Date.now() - startedAt) / 1000);
    let score=0, correct=0, wrong=0, unanswered=0;
    questions.forEach((q,i) => {
      const ua=answers[i];
      if(!ua) unanswered++;
      else if(ua===q.ans){correct++;score+=2;}
      else{wrong++;score-=0.5;}
    });
    score = Math.max(0, Math.round(score*10)/10);
    const accuracy = Math.round(correct/questions.length*100);
    const result   = {score,correct,wrong,unanswered,accuracy,timeTaken:elapsed};
    setMyResult(result);
    if(myGroup) await submitGroupResult(myGroup.id, result);

    /* build participants snapshot for History page */
    const activeMembers = (myGroup?.members||[]).filter(id=>!myGroup?.quit?.[id]);
    const allResults    = {...(myGroup?.results||{}), [user.id]:result};
    const participants  = activeMembers.map(id=>{
      const u=id===user?.id?user:(users.find(x=>x.id===id)||{name:"Unknown"});
      const r=allResults[id]||{};
      return {name:u.name,score:r.score||0,correct:r.correct||0,wrong:r.wrong||0,accuracy:r.accuracy||0};
    }).sort((a,b)=>b.score-a.score);
    const myRank = participants.findIndex(p=>p.name===user?.name)+1;

    await addResult({
      title:`Group Mock (${activeMembers.length}p)`,
      isMock:true, isGroup:true,
      participants, myRank,
      ...result
    });
    setPhase("waiting");
  }

  /* ── quit mid-exam ── */
  async function handleQuit() {
    if (!window.confirm("Quit the exam? You will NOT be able to see the group results.")) return;
    clearInterval(timerRef.current);
    if (myGroup) await quitGroup(myGroup.id);
    setPhase("lobby");
    setQuestions([]); setAnswers({}); setMyResult(null);
  }

  const timerPct   = timeLeft / TOTAL_SECS * 100;
  const timerColor = timerPct > 50 ? "#4ade80" : timerPct > 20 ? "#fbbf24" : "#f87171";

  /* ── helpers ── */
  function getUser(id) { return id===user?.id ? user : (users.find(x=>x.id===id)||{name:"Unknown",profile:{}}); }

  /* ═════ LOSER POPUP ════════════════════════════════════════ */
  function LoserPopup() {
    if (!loserData) return null;
    return (
      <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.92)",zIndex:3000,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}>
        <div style={{background:T?"#0e0e1c":"#fff",border:"2px solid rgba(239,68,68,0.45)",borderRadius:24,padding:"40px 36px",maxWidth:440,width:"100%",textAlign:"center"}}>
          <div style={{fontSize:72,marginBottom:10}}>💔</div>
          <div style={{fontSize:20,fontWeight:900,color:"#f87171",marginBottom:6}}>
            {loserData.isMe ? "You Finished Last!" : `${loserData.name} Finished Last!`}
          </div>
          <div style={{fontSize:30,fontWeight:900,lineHeight:1.4,margin:"18px 0",background:"linear-gradient(135deg,#f87171,#fbbf24,#4ade80)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>
            "Every winner was once a loser."
          </div>
          <div style={{fontSize:14,color:sub,marginBottom:28,lineHeight:1.7}}>
            {loserData.isMe ? "Don't quit. Keep practising! 💪🔥" : `Keep encouraging ${loserData.name}! 💪`}
          </div>
          <button onClick={() => setLoserData(null)} style={{...Btn("primary"),width:"100%",padding:"13px"}}>
            See Full Results →
          </button>
        </div>
      </div>
    );
  }

  /* ═════ QUIT NOTIFICATIONS ════════════════════════════════ */
  function QuitNotifs() {
    return (
      <div style={{position:"fixed",top:16,right:16,zIndex:2000,display:"flex",flexDirection:"column",gap:8}}>
        {quitNotifs.map((n,i) => (
          <div key={i} style={{padding:"12px 18px",background:"rgba(239,68,68,0.92)",borderRadius:10,color:"#fff",fontSize:13,fontWeight:700,boxShadow:"0 4px 20px rgba(0,0,0,0.4)"}}>
            ⚠️ {n.name} has left the exam.
          </div>
        ))}
      </div>
    );
  }

  /* ═════════════════════════════════════════════════════════════
     PHASE: RUNNING
  ═════════════════════════════════════════════════════════════ */
  if (phase === "running" && questions.length > 0) {
    const q        = questions[curr];
    const userAns  = answers[curr];
    const answered = Object.keys(answers).length;

    return (
      <div>
        <QuitNotifs />
        <div style={{display:"grid",gridTemplateColumns:"1fr 220px",gap:14,alignItems:"start"}}>

          {/* left: question */}
          <div>
            {/* status bar */}
            <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:11,padding:"10px 16px",marginBottom:12,display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:8}}>
              <span style={{padding:"4px 12px",borderRadius:20,background:"rgba(79,142,247,0.12)",border:"1px solid rgba(79,142,247,0.25)",fontSize:11,fontWeight:800,color:"#7aadff"}}>👥 GROUP MOCK · Q{curr+1}/{questions.length}</span>
              <div style={{display:"flex",alignItems:"center",gap:8}}>
                <div style={{width:100,height:5,background:T?"rgba(255,255,255,0.06)":"#eee",borderRadius:3,overflow:"hidden"}}>
                  <div style={{height:"100%",width:`${timerPct}%`,background:`linear-gradient(90deg,${timerColor},${timerColor}88)`,transition:"width 1s linear"}}/>
                </div>
                <span style={{fontFamily:"'JetBrains Mono',monospace",fontWeight:900,color:timerColor,fontSize:18,minWidth:68}}>{fmt(timeLeft)}</span>
              </div>
              <span style={{fontSize:12,color:sub}}>{answered}/{questions.length} answered</span>
            </div>

            {/* question card */}
            <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:14,padding:"22px 24px",marginBottom:12}}>
              <div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}>
                <span style={{padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:700,background:"rgba(79,142,247,0.12)",color:"#7aadff",border:"1px solid rgba(79,142,247,0.2)"}}>{q.subject}</span>
                <span style={{padding:"3px 10px",borderRadius:20,fontSize:11,background:T?"rgba(255,255,255,0.05)":"#f3f4f6",color:sub}}>{q.chapter}</span>
              </div>
              <div style={{fontSize:16,fontWeight:600,color:txt,lineHeight:1.75,marginBottom:22}}>{q.q}</div>
              {q.opts.map((opt,i) => {
                const sel = userAns===opt;
                return (
                  <button key={opt} onClick={() => setAnswers(a=>({...a,[curr]:opt}))}
                    style={{display:"flex",alignItems:"center",gap:12,width:"100%",textAlign:"left",padding:"13px 16px",borderRadius:10,border:`1.5px solid ${sel?"#4f8ef7":"rgba(255,255,255,0.08)"}`,background:sel?"rgba(79,142,247,0.13)":T?"rgba(255,255,255,0.02)":"#f9fafb",color:sel?"#7aadff":T?"#ccc":"#444",cursor:"pointer",fontSize:14,fontWeight:sel?700:400,marginBottom:8,fontFamily:"inherit",transition:"all 0.15s"}}>
                    <span style={{width:28,height:28,borderRadius:"50%",background:sel?"#4f8ef722":T?"rgba(255,255,255,0.07)":"#eee",border:`1.5px solid ${sel?"#4f8ef7":"transparent"}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:800,flexShrink:0,color:sel?"#4f8ef7":sub}}>
                      {["A","B","C","D"][i]}
                    </span>
                    {opt}
                  </button>
                );
              })}
            </div>

            <div style={{display:"flex",gap:10}}>
              <button style={Btn("ghost")} onClick={() => setCurr(c=>Math.max(0,c-1))} disabled={curr===0}>← Prev</button>
              <button style={Btn("ghost")} onClick={() => setCurr(c=>Math.min(questions.length-1,c+1))} disabled={curr===questions.length-1}>Next →</button>
              <div style={{flex:1}}/>
              <button style={{...Btn("danger"),fontSize:12}} onClick={handleQuit}>✕ Quit</button>
              <button style={Btn("danger")} onClick={() => { if(window.confirm("Submit your test? Cannot change answers.")) doSubmit(); }}>
                Submit Test
              </button>
            </div>
          </div>

          {/* right: players + palette */}
          <div style={{display:"flex",flexDirection:"column",gap:12}}>
            <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:12,padding:14}}>
              <div style={{fontSize:12,fontWeight:800,color:sub,marginBottom:10,textTransform:"uppercase",letterSpacing:"0.05em"}}>👥 Players</div>
              {myGroup?.members.map(id => {
                const u    = getUser(id);
                const done = myGroup?.results?.[id];
                const quit = myGroup?.quit?.[id];
                return (
                  <div key={id} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:`1px solid ${cardBr}`}}>
                    <div style={{width:30,height:30,borderRadius:"50%",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:800,color:"#fff",flexShrink:0}}>
                      {u?.name?.[0]||"?"}
                    </div>
                    <div style={{flex:1}}>
                      <div style={{fontSize:12,fontWeight:id===user.id?800:500,color:id===user.id?"#7aadff":quit?"#f87171":txt}}>
                        {u?.name||"Unknown"}{id===user.id?" (You)":""}
                      </div>
                    </div>
                    <span style={{fontSize:18}}>{quit?"🚫":done?"✅":"⏳"}</span>
                  </div>
                );
              })}
            </div>

            <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:12,padding:14}}>
              <div style={{fontSize:12,fontWeight:800,color:sub,marginBottom:10,textTransform:"uppercase",letterSpacing:"0.05em"}}>Question Palette</div>
              <div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:10}}>
                {questions.map((_,i) => {
                  const done=answers[i]!==undefined, active=i===curr;
                  return (
                    <button key={i} onClick={() => setCurr(i)}
                      style={{width:28,height:28,borderRadius:5,border:`1.5px solid ${active?"#4f8ef7":done?"rgba(79,142,247,0.4)":T?"rgba(255,255,255,0.08)":"#e5e7eb"}`,background:active?"#4f8ef7":done?"rgba(79,142,247,0.18)":T?"rgba(255,255,255,0.03)":"#f9fafb",color:active?"#fff":done?"#7aadff":sub,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"inherit",transition:"all 0.1s"}}>
                      {i+1}
                    </button>
                  );
                })}
              </div>
              <div style={{fontSize:11,color:sub}}>Done: <b style={{color:"#4ade80"}}>{answered}</b> &nbsp;|&nbsp; Left: <b style={{color:"#f87171"}}>{questions.length-answered}</b></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ═════ PHASE: WAITING ════════════════════════════════════ */
  if (phase === "waiting") {
    const submitted = Object.keys(myGroup?.results||{}).length;
    const total     = (myGroup?.members?.filter(id=>!myGroup?.quit?.[id])?.length)||0;
    return (
      <div style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:"65vh"}}>
        <LoserPopup />
        <div style={{textAlign:"center",maxWidth:460,width:"100%"}}>
          <div style={{fontSize:64,marginBottom:12}}>⏳</div>
          <div style={{fontSize:22,fontWeight:900,color:txt,marginBottom:6}}>Submitted! Waiting…</div>
          <div style={{color:sub,fontSize:13,marginBottom:24}}>Waiting for other players to finish.</div>
          <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:16,padding:22,marginBottom:16}}>
            <div style={{fontSize:14,fontWeight:800,color:txt,marginBottom:14}}>Submission Status</div>
            {myGroup?.members.map(id => {
              const u    = getUser(id);
              const done = myGroup?.results?.[id];
              const quit = myGroup?.quit?.[id];
              return (
                <div key={id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderBottom:`1px solid ${cardBr}`}}>
                  <div style={{width:38,height:38,borderRadius:"50%",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:800,color:"#fff",flexShrink:0}}>
                    {u?.name?.[0]||"?"}
                  </div>
                  <div style={{flex:1,textAlign:"left"}}>
                    <div style={{fontSize:13,fontWeight:id===user.id?800:500,color:quit?"#f87171":id===user.id?"#7aadff":txt}}>
                      {u?.name||"Unknown"}{id===user.id?" (You)":""}
                    </div>
                    {done&&<div style={{fontSize:11,color:"#4ade80"}}>{myGroup.results[id].score} marks · {myGroup.results[id].accuracy}% acc</div>}
                    {quit&&<div style={{fontSize:11,color:"#f87171"}}>Quit early</div>}
                  </div>
                  <div style={{fontSize:24}}>{quit?"🚫":done?"✅":"⏳"}</div>
                </div>
              );
            })}
          </div>
          <div style={{fontSize:13,color:"#4f8ef7",fontWeight:700}}>{submitted}/{total} submitted</div>
          <div style={{width:`${total>0?(submitted/total)*100:0}%`,height:4,background:"linear-gradient(90deg,#4f8ef7,#a855f7)",borderRadius:4,margin:"12px auto 0",transition:"width 0.5s"}}/>
        </div>
      </div>
    );
  }

  /* ═════ PHASE: DONE — RESULTS ═════════════════════════════ */
  if (phase === "done" && myGroup) {
    const medals       = ["🥇","🥈","🥉","💔"];
    const rankLabels   = ["1st","2nd","3rd","Loser"];
    const activeMembers = myGroup.members.filter(id => !myGroup.quit?.[id]);
    const quitMembers   = myGroup.members.filter(id => myGroup.quit?.[id]);
    const ranked = activeMembers
      .map(id => {
        const u = getUser(id);
        const r = myGroup.results[id] || {};
        return {id,name:u.name,branch:u.profile?.branch||"—",score:r.score||0,correct:r.correct||0,wrong:r.wrong||0,unanswered:r.unanswered||0,accuracy:r.accuracy||0,time:r.timeTaken||0};
      })
      .sort((a,b) => b.score - a.score);

    return (
      <div>
        <LoserPopup />

        <div style={{textAlign:"center",marginBottom:28}}>
          <div style={{fontSize:56,marginBottom:8}}>🏆</div>
          <div style={{fontSize:26,fontWeight:900,color:txt}}>Group Mock Results</div>
          <div style={{color:sub,fontSize:13,marginTop:4}}>{new Date().toLocaleDateString("en-IN")} · {activeMembers.length} Players</div>
        </div>

        {/* Podium */}
        <div style={{display:"flex",justifyContent:"center",gap:12,marginBottom:28,flexWrap:"wrap"}}>
          {ranked.map((m,i) => {
            const isWinner = i===0, isLoser = i===ranked.length-1&&ranked.length>1;
            return (
              <div key={m.id} style={{background:isWinner?"linear-gradient(135deg,rgba(251,191,36,0.2),rgba(251,191,36,0.04))":isLoser?"linear-gradient(135deg,rgba(239,68,68,0.12),transparent)":cardBg,border:`2px solid ${isWinner?"#fbbf24":isLoser?"rgba(239,68,68,0.4)":cardBr}`,borderRadius:18,padding:"24px 20px",textAlign:"center",minWidth:155,flex:"1 1 140px",maxWidth:195,position:"relative"}}>
                <div style={{fontSize:40,marginBottom:6}}>{medals[i]||"🏅"}</div>
                <div style={{width:48,height:48,borderRadius:"50%",background:`linear-gradient(135deg,hsl(${i*80}deg,70%,55%),hsl(${i*80+60}deg,65%,40%))`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:19,fontWeight:900,color:"#fff",margin:"0 auto 10px"}}>
                  {m.name[0]}
                </div>
                <div style={{fontWeight:900,fontSize:14,color:isLoser?"#f87171":isWinner?"#fbbf24":txt,marginBottom:2}}>{m.name}</div>
                <div style={{fontSize:10,color:sub,marginBottom:8}}>{m.branch}</div>
                <div style={{fontSize:28,fontWeight:900,color:isLoser?"#f87171":isWinner?"#fbbf24":"#4f8ef7",lineHeight:1}}>{m.score}</div>
                <div style={{fontSize:10,color:sub,marginBottom:4}}>/200 marks</div>
                <div style={{fontSize:14,fontWeight:800,padding:"3px 10px",borderRadius:20,display:"inline-block",background:isLoser?"rgba(239,68,68,0.12)":isWinner?"rgba(251,191,36,0.15)":"rgba(79,142,247,0.12)",color:isLoser?"#f87171":isWinner?"#fbbf24":"#7aadff"}}>
                  {rankLabels[i]||`#${i+1}`}
                </div>
                {m.id===user.id&&<div style={{position:"absolute",top:8,right:8,fontSize:9,padding:"2px 6px",borderRadius:8,background:"rgba(79,142,247,0.2)",color:"#7aadff",fontWeight:800}}>YOU</div>}
              </div>
            );
          })}
        </div>

        {/* Full table */}
        <div style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:16,padding:22,marginBottom:16}}>
          <div style={{fontSize:15,fontWeight:800,color:txt,marginBottom:14}}>📊 Full Comparison</div>
          <div style={{display:"grid",gridTemplateColumns:"2fr 80px 80px 70px 90px 70px",gap:6,padding:"9px 12px",background:T?"rgba(255,255,255,0.05)":"#f5f5f5",borderRadius:9,marginBottom:4,fontSize:11,color:sub,fontWeight:800,textTransform:"uppercase",letterSpacing:"0.04em"}}>
            <span>Player</span><span>Score</span><span>Correct</span><span>Wrong</span><span>Accuracy</span><span>Rank</span>
          </div>
          {ranked.map((m,i) => {
            const isWinner=i===0, isLoser=i===ranked.length-1&&ranked.length>1;
            return (
              <div key={m.id} style={{display:"grid",gridTemplateColumns:"2fr 80px 80px 70px 90px 70px",gap:6,padding:"12px 12px",borderBottom:`1px solid ${T?"rgba(255,255,255,0.04)":"#f0f0f0"}`,alignItems:"center",background:m.id===user.id?T?"rgba(79,142,247,0.07)":"rgba(79,142,247,0.04)":"transparent"}}>
                <div style={{display:"flex",alignItems:"center",gap:8}}>
                  <span style={{fontSize:18}}>{medals[i]||"🏅"}</span>
                  <div>
                    <div style={{fontSize:13,fontWeight:m.id===user.id?900:500,color:isWinner?"#fbbf24":isLoser?"#f87171":m.id===user.id?"#7aadff":txt}}>
                      {m.name}{m.id===user.id?" (You)":""}
                    </div>
                    <div style={{fontSize:10,color:sub}}>{m.branch}</div>
                  </div>
                </div>
                <span style={{fontSize:16,fontWeight:900,color:isWinner?"#fbbf24":isLoser?"#f87171":"#4f8ef7"}}>{m.score}</span>
                <span style={{fontSize:13,fontWeight:700,color:"#4ade80"}}>{m.correct}</span>
                <span style={{fontSize:13,fontWeight:700,color:"#f87171"}}>{m.wrong}</span>
                <div>
                  <span style={{fontSize:13,fontWeight:700,color:m.accuracy>=60?"#4ade80":"#f87171"}}>{m.accuracy}%</span>
                  <div style={{height:3,background:T?"rgba(255,255,255,0.06)":"#eee",borderRadius:2,marginTop:3,overflow:"hidden"}}>
                    <div style={{height:"100%",width:`${m.accuracy}%`,background:`linear-gradient(90deg,${m.accuracy>=60?"#4ade80":"#f87171"},transparent)`,borderRadius:2}}/>
                  </div>
                </div>
                <span style={{fontSize:13,fontWeight:800,color:isLoser?"#f87171":isWinner?"#fbbf24":"#7aadff"}}>{rankLabels[i]||`#${i+1}`}</span>
              </div>
            );
          })}
          {quitMembers.length > 0 && (
            <div style={{marginTop:12,padding:"10px 12px",background:"rgba(239,68,68,0.06)",borderRadius:8}}>
              <div style={{fontSize:12,color:"#f87171",fontWeight:700}}>
                🚫 Quit Early (not ranked): {quitMembers.map(id=>getUser(id).name).join(", ")}
              </div>
            </div>
          )}
        </div>

        <div style={{display:"flex",gap:12,flexWrap:"wrap"}}>
          <button style={Btn("primary")} onClick={() => downloadGroupPDF(myGroup, users, user, nextMockNum)}>
            ⬇ Download PDF (ranklify.mocktest{nextMockNum}.pdf)
          </button>
          <button style={Btn("ghost")} onClick={() => { setPhase("lobby"); setMyResult(null); setLoserData(null); }}>
            ← Back to Lobby
          </button>
        </div>
      </div>
    );
  }

  /* ═════════════════════════════════════════════════════════════
     PHASE: LOBBY
  ═════════════════════════════════════════════════════════════ */
  return (
    <div>
      <div style={{fontSize:22,fontWeight:900,color:txt,marginBottom:4}}>Group Mock Test</div>
      <div style={{color:sub,fontSize:13,marginBottom:20}}>
        Challenge up to 3 friends. Same questions, same time, ranked results. 🏆
      </div>

      {/* Pending invites */}
      {pendingInvites.length > 0 && (
        <div style={{background:"rgba(79,142,247,0.07)",border:"2px solid rgba(79,142,247,0.35)",borderRadius:14,padding:20,marginBottom:22}}>
          <div style={{fontSize:15,fontWeight:900,color:"#7aadff",marginBottom:14}}>📨 Group Mock Invites ({pendingInvites.length})</div>
          {pendingInvites.map(inv => {
            const host = users.find(u=>u.id===inv.from);
            const grp  = groups.find(g=>g.id===inv.groupId);
            return (
              <div key={inv.id} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 0",borderBottom:"1px solid rgba(79,142,247,0.12)"}}>
                <div style={{width:44,height:44,borderRadius:"50%",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17,fontWeight:800,color:"#fff",flexShrink:0}}>
                  {host?.name?.[0]||"?"}
                </div>
                <div style={{flex:1}}>
                  <div style={{fontWeight:800,color:txt,fontSize:14}}>
                    <span style={{color:"#7aadff"}}>{host?.name||"Someone"}</span> invited you!
                  </div>
                  <div style={{fontSize:11,color:sub,marginTop:2}}>{grp?.members?.length||1} player(s) · 100 Qs · 120 min</div>
                </div>
                <button onClick={() => acceptGroupInvite(inv.id)} style={{...Btn("green"),padding:"8px 16px",fontSize:12,marginRight:6}}>✓ Join</button>
                <button onClick={() => rejectGroupInvite(inv.id)} style={{...Btn("danger"),padding:"8px 14px",fontSize:12}}>✕</button>
              </div>
            );
          })}
        </div>
      )}

      {myGroup ? (
        /* ── Active Session: Lobby + Ready System ── */
        <div style={{background:cardBg,border:"2px solid rgba(79,142,247,0.35)",borderRadius:16,padding:24}}>
          <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",marginBottom:20,gap:12,flexWrap:"wrap"}}>
            <div>
              <div style={{fontSize:17,fontWeight:900,color:txt}}>
                {myGroup.host===user.id ? "🎮 Your Session" : "🎮 Active Session"}
              </div>
              <div style={{fontSize:12,color:sub,marginTop:3}}>
                Status: <b style={{color:myGroup.status==="lobby"?"#fbbf24":"#4ade80",textTransform:"uppercase"}}>{myGroup.status}</b>
                &nbsp;·&nbsp; {myGroup.members.length}/4 players
              </div>
            </div>
            {/* Host: Start button (only when all members ready) */}
            {myGroup.host===user.id && myGroup.status==="lobby" && (() => {
              const allReady = myGroup.members.every(id => myGroup.ready?.[id]);
              const enoughPlayers = myGroup.members.length >= 2;
              return (
                <button
                  onClick={() => {
                    if (!enoughPlayers) { alert("Need at least 2 players!"); return; }
                    if (!allReady) { alert("Wait for all players to click READY!"); return; }
                    startGroupSession(myGroup.id);
                  }}
                  style={{...Btn("green"),opacity:(enoughPlayers&&allReady)?1:0.45}}>
                  🚀 Start Exam for Everyone
                </button>
              );
            })()}
          </div>

          {/* ── PLAYER SLOTS (2–4) ── */}
          <div style={{marginBottom:20}}>
            <div style={{fontSize:12,fontWeight:800,color:sub,marginBottom:12,textTransform:"uppercase",letterSpacing:"0.04em"}}>
              Player Slots (max 4)
            </div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:10}}>
              {[0,1,2,3].map(slot => {
                const memberId = myGroup.members[slot];
                const u        = memberId ? getUser(memberId) : null;
                const isReady  = memberId && myGroup.ready?.[memberId];
                const isHost   = memberId === myGroup.host;
                const isMe     = memberId === user?.id;
                return (
                  <div key={slot} style={{background:u?isReady?"rgba(74,222,128,0.08)":T?"rgba(255,255,255,0.04)":"#f9fafb":T?"rgba(255,255,255,0.02)":"#f3f4f6",border:`2px solid ${u?isReady?"rgba(74,222,128,0.45)":T?"rgba(255,255,255,0.1)":"#e5e7eb":"rgba(255,255,255,0.04)"}`,borderRadius:14,padding:"18px 16px",textAlign:"center",minHeight:130,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8}}>
                    {u ? (
                      <>
                        {/* avatar */}
                        <div style={{width:52,height:52,borderRadius:"50%",background:`linear-gradient(135deg,hsl(${slot*80}deg,65%,55%),hsl(${slot*80+60}deg,65%,40%))`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,fontWeight:900,color:"#fff",border:`3px solid ${isReady?"#4ade80":"transparent"}`,boxShadow:isReady?"0 0 12px rgba(74,222,128,0.4)":"none",transition:"all 0.3s"}}>
                          {u.name[0].toUpperCase()}
                        </div>
                        <div style={{fontSize:13,fontWeight:800,color:isMe?"#7aadff":txt}}>{u.name}{isMe?" (You)":""}</div>
                        {isHost&&<div style={{fontSize:9,padding:"2px 8px",borderRadius:20,background:"rgba(251,191,36,0.15)",color:"#fbbf24",fontWeight:800}}>👑 HOST</div>}
                        {/* ready badge / button */}
                        {isReady ? (
                          <div style={{fontSize:11,padding:"4px 12px",borderRadius:20,background:"rgba(74,222,128,0.15)",color:"#4ade80",fontWeight:800}}>✓ READY</div>
                        ) : isMe ? (
                          <button onClick={() => setReady(myGroup.id)}
                            style={{fontSize:11,padding:"6px 16px",borderRadius:20,border:"none",cursor:"pointer",background:"linear-gradient(135deg,#4ade80,#22c55e)",color:"#fff",fontWeight:800,fontFamily:"inherit"}}>
                            Click READY
                          </button>
                        ) : (
                          <div style={{fontSize:11,padding:"4px 12px",borderRadius:20,background:T?"rgba(255,255,255,0.06)":"#f0f0f0",color:sub,fontWeight:700}}>Not Ready</div>
                        )}
                      </>
                    ) : (
                      <>
                        <div style={{width:52,height:52,borderRadius:"50%",background:T?"rgba(255,255,255,0.04)":"#e5e7eb",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,color:sub}}>?</div>
                        <div style={{fontSize:13,color:sub,fontWeight:700}}>Waiting…</div>
                        <div style={{fontSize:11,color:T?"rgba(255,255,255,0.2)":"#ddd"}}>Empty Slot</div>
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Ready status summary */}
          {myGroup.status==="lobby" && (() => {
            const readyCount  = myGroup.members.filter(id=>myGroup.ready?.[id]).length;
            const totalCount  = myGroup.members.length;
            const allReady    = readyCount === totalCount;
            return (
              <div style={{padding:"12px 16px",background:allReady?"rgba(74,222,128,0.08)":"rgba(251,191,36,0.06)",border:`1.5px solid ${allReady?"rgba(74,222,128,0.35)":"rgba(251,191,36,0.3)"}`,borderRadius:10,marginBottom:16,display:"flex",alignItems:"center",gap:10}}>
                <span style={{fontSize:20}}>{allReady?"✅":"⏳"}</span>
                <span style={{fontSize:13,fontWeight:700,color:allReady?"#4ade80":"#fbbf24"}}>
                  {allReady ? "All players ready! Host can now start the exam." : `${readyCount}/${totalCount} players ready. Waiting for everyone to click READY.`}
                </span>
              </div>
            );
          })()}

          {/* Invite panel (host only, lobby only, < 4 members) */}
          {myGroup.host===user.id && myGroup.status==="lobby" && myGroup.members.length < 4 && (
            <div style={{borderTop:`1px solid ${cardBr}`,paddingTop:18}}>
              <div style={{fontSize:14,fontWeight:900,color:txt,marginBottom:4}}>
                👥 Invite Friends &nbsp;
                <span style={{fontSize:12,color:sub,fontWeight:400}}>({myGroup.members.length}/4 slots)</span>
              </div>
              {connections.length===0 ? (
                <div style={{padding:16,background:T?"rgba(255,255,255,0.03)":"#f9fafb",borderRadius:10,fontSize:13,color:sub,textAlign:"center"}}>
                  No connections yet. Go to <b style={{color:"#4f8ef7"}}>Explore Students</b> first.
                </div>
              ) : (
                <div style={{display:"flex",flexDirection:"column",gap:8}}>
                  {connections.filter(c=>!myGroup.members.includes(c.id)).map(c => {
                    const alreadyInvited = invites.some(i=>i.groupId===myGroup.id&&i.to===c.id&&i.status==="pending");
                    const accepted       = invites.some(i=>i.groupId===myGroup.id&&i.to===c.id&&i.status==="accepted");
                    return (
                      <div key={c.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:T?"rgba(255,255,255,0.03)":"#f9fafb",borderRadius:11,border:`1px solid ${cardBr}`}}>
                        <div style={{width:38,height:38,borderRadius:"50%",background:"linear-gradient(135deg,#a855f7,#6366f1)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:800,color:"#fff",flexShrink:0}}>{c.name[0]}</div>
                        <div style={{flex:1}}>
                          <div style={{fontSize:14,fontWeight:800,color:txt}}>{c.name}</div>
                          <div style={{fontSize:11,color:sub}}>@{c.socialProfile?.username||"—"} · {c.profile?.branch}</div>
                        </div>
                        <button
                          disabled={alreadyInvited||accepted}
                          onClick={() => sendGroupInvite(myGroup.id,c.id)}
                          style={{padding:"8px 18px",borderRadius:9,border:"none",cursor:alreadyInvited||accepted?"default":"pointer",background:accepted?"rgba(74,222,128,0.15)":alreadyInvited?"rgba(251,191,36,0.15)":"linear-gradient(135deg,#4f8ef7,#a855f7)",color:accepted?"#4ade80":alreadyInvited?"#fbbf24":"#fff",fontSize:12,fontWeight:800,fontFamily:"inherit"}}>
                          {accepted?"✓ Joined":alreadyInvited?"⏳ Invited":"Invite →"}
                        </button>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* Non-host message */}
          {myGroup.host!==user.id && myGroup.status==="lobby" && !myGroup.ready?.[user.id] && (
            <div style={{marginTop:12,padding:"12px 16px",background:"rgba(79,142,247,0.07)",border:"1px solid rgba(79,142,247,0.2)",borderRadius:10,fontSize:13,color:"#7aadff",fontWeight:600}}>
              ⚡ Click the <b>READY</b> button in your slot above to confirm you're ready!
            </div>
          )}
        </div>

      ) : (
        /* ── No active session ── */
        <>
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(170px,1fr))",gap:12,marginBottom:24}}>
            {[
              {icon:"👥",t:"2–4 Players",    d:"Max 4 per session"},
              {icon:"✋",t:"Ready System",    d:"Everyone confirms before start"},
              {icon:"⚡",t:"Synchronized",   d:"Same questions, same time"},
              {icon:"🚫",t:"Quit Detection", d:"Quitters can't see results"},
              {icon:"🏆",t:"Ranked Results", d:"1st to Loser placement"},
              {icon:"📄",t:"Group PDF",      d:"ranklify.mocktestN.pdf"},
            ].map(c => (
              <div key={c.t} style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:12,padding:"18px 16px",textAlign:"center"}}>
                <div style={{fontSize:28,marginBottom:8}}>{c.icon}</div>
                <div style={{fontWeight:800,color:txt,fontSize:13}}>{c.t}</div>
                <div style={{fontSize:11,color:sub,marginTop:3}}>{c.d}</div>
              </div>
            ))}
          </div>
          <button onClick={() => createGroup()} style={{...Btn("primary"),padding:"14px 36px",fontSize:15}}>
            🚀 Create Group Session
          </button>
          <div style={{fontSize:12,color:sub,marginTop:10}}>
            After creating, invite friends and wait for all to click READY.
          </div>
        </>
      )}
    </div>
  );
}
