/*
 * GroupMock.jsx – Ranklify v5
 * Full invite flow, real-time polling, same seeded questions,
 * ranked results, loser popup with motivational quote
 */
import { useState, useEffect, useRef } from "react";
import { QUESTION_BANK } from "../data/subjects";
import { useApp } from "../context/AppContext";

/* ─── seeded deterministic shuffle (same seed = same order) ─── */
function seededShuffle(arr, seed) {
  const a = [...arr];
  let s = (seed % 2147483647) || 1;
  for (let i = a.length - 1; i > 0; i--) {
    s = (s * 16807) % 2147483647;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/* ─── build 100-question paper from seed ─────────────────────── */
function buildPaper(seed) {
  const base = seededShuffle([...QUESTION_BANK], seed);
  let pool = [...base];
  while (pool.length < 100) pool = [...pool, ...base];
  return pool.slice(0, 100);
}

/* ─── print group PDF ─────────────────────────────────────────── */
function printGroupPDF(group, users, me) {
  const ranked = group.members
    .map(id => {
      const u = id === me.id ? me : (users.find(x => x.id === id) || { name: "Unknown", profile: {} });
      const r = group.results[id] || {};
      return { name: u.name, branch: u.profile?.branch || "—", score: r.score || 0, correct: r.correct || 0, wrong: r.wrong || 0, accuracy: r.accuracy || 0, time: r.timeTaken || 0 };
    })
    .sort((a, b) => b.score - a.score);

  const medals = ["🥇", "🥈", "🥉", "💔"];
  const html = `<!DOCTYPE html><html><head><title>Ranklify Group Mock</title>
<style>body{font-family:Arial;padding:28px;color:#222;max-width:860px;margin:0 auto}
h1{color:#4f8ef7;font-size:21px;margin:0 0 4px}p.sub{color:#888;font-size:11px;margin:0 0 18px}
table{width:100%;border-collapse:collapse;font-size:13px}
th{background:linear-gradient(135deg,#4f8ef7,#a855f7);color:#fff;padding:11px 13px;text-align:left}
td{padding:10px 13px;border-bottom:1px solid #eee}
tr:nth-child(even) td{background:#f9f9f9}
.gold td{background:rgba(251,191,36,0.1)!important}
.foot{margin-top:24px;color:#aaa;font-size:10px;text-align:center}</style>
</head><body>
<div style="font-size:22px;font-weight:900;color:#4f8ef7">⚡ Ranklify</div>
<p class="sub">DDCET Group Mock Test · ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</p>
<h1>Group Mock Results — ${ranked.length} Players</h1>
<p style="background:#f0fdf4;color:#166534;padding:10px;border-radius:6px;font-size:13px">
  🏆 Winner: <b>${ranked[0]?.name}</b> — ${ranked[0]?.score} marks (${ranked[0]?.accuracy}% accuracy)</p>
<table><thead><tr><th>Rank</th><th>Name</th><th>Branch</th><th>Score /200</th><th>Correct</th><th>Wrong</th><th>Accuracy</th><th>Time</th></tr></thead><tbody>
${ranked.map((m, i) => `<tr class="${i === 0 ? "gold" : ""}">
  <td>${medals[i] || "#" + (i + 1)}</td><td><b>${m.name}</b></td><td>${m.branch}</td>
  <td style="color:#4f8ef7;font-weight:800">${m.score}</td>
  <td style="color:#16a34a">${m.correct}</td><td style="color:#dc2626">${m.wrong}</td>
  <td>${m.accuracy}%</td><td>${Math.floor(m.time / 60)}m ${m.time % 60}s</td></tr>`).join("")}
</tbody></table>
<p class="foot">Generated by Ranklify · Same Questions · Same Time · Same Marking</p>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) return alert("Please allow popups for PDF download.");
  w.document.write(html); w.document.close(); setTimeout(() => w.print(), 400);
}

/* ─── format seconds mm:ss ───────────────────────────────────── */
const fmt = s => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`;

const TOTAL_SECS = 120 * 60;

/* ═══════════════════════════════════════════════════════════════ */
export default function GroupMock() {
  const {
    user, users, darkMode, groups, invites,
    myConnections, createGroup, sendGroupInvite,
    acceptGroupInvite, rejectGroupInvite,
    startGroupSession, submitGroupResult, myGroupInvites,
    addResult,
  } = useApp();

  /* ── theme ── */
  const txt    = darkMode ? "#e2e2f0" : "#111";
  const sub    = darkMode ? "#555"    : "#888";
  const cardBg = darkMode ? "rgba(255,255,255,0.03)"  : "#fff";
  const cardBr = darkMode ? "rgba(255,255,255,0.07)"  : "#e5e7eb";
  const Btn = (v = "primary") => ({
    padding: "10px 22px", borderRadius: 9, border: "none", cursor: "pointer",
    fontSize: 13, fontWeight: 700, fontFamily: "inherit",
    background: v === "primary" ? "linear-gradient(135deg,#4f8ef7,#a855f7)"
              : v === "green"   ? "linear-gradient(135deg,#4ade80,#22c55e)"
              : v === "danger"  ? "rgba(239,68,68,0.15)"
              : darkMode        ? "rgba(255,255,255,0.07)" : "#f3f4f6",
    color: (v === "primary" || v === "green") ? "#fff" : v === "danger" ? "#f87171" : txt,
  });

  /* ── state ── */
  const [phase,     setPhase]     = useState("lobby");   // lobby | running | waiting | done
  const [questions, setQuestions] = useState([]);
  const [answers,   setAnswers]   = useState({});
  const [curr,      setCurr]      = useState(0);
  const [timeLeft,  setTimeLeft]  = useState(TOTAL_SECS);
  const [startedAt, setStartedAt] = useState(null);
  const [myResult,  setMyResult]  = useState(null);
  const [loserData, setLoserData] = useState(null);   // { name, isMe }
  const timerRef = useRef(null);

  /* ── my active group (any non-done session I'm in) ── */
  const myGroup = groups.find(g => g.members.includes(user?.id) && g.status !== "done") || null;

  /* ── pending invites for ME ── */
  const pendingInvites = myGroupInvites ? myGroupInvites() : [];

  /* ── connections I can invite (all accepted followers/following) ── */
  const connections = myConnections ? myConnections() : [];

  /* ── watch for group status changes ── */
  useEffect(() => {
    if (!myGroup) return;

    if (myGroup.status === "running" && phase === "lobby") {
      const qs = buildPaper(myGroup.seed);
      setQuestions(qs);
      setAnswers({}); setCurr(0);
      setTimeLeft(TOTAL_SECS); setStartedAt(Date.now());
      setPhase("running");
    }

    if (myGroup.status === "done" && (phase === "running" || phase === "waiting")) {
      setPhase("done");
      const ranked = myGroup.members
        .map(id => ({ id, score: myGroup.results[id]?.score || 0 }))
        .sort((a, b) => b.score - a.score);
      const loserId = ranked[ranked.length - 1]?.id;
      const loserU  = loserId === user.id ? user : users.find(u => u.id === loserId);
      setLoserData({ name: loserU?.name || "Unknown", isMe: loserId === user.id });
    }
  }, [myGroup?.status, myGroup?.members?.length]);

  /* ── timer ── */
  useEffect(() => {
    if (phase !== "running") return;
    timerRef.current = setInterval(() => {
      setTimeLeft(t => {
        if (t <= 1) { clearInterval(timerRef.current); doSubmit(); return 0; }
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(timerRef.current);
  }, [phase]);

  /* ── submit my answers ── */
  function doSubmit() {
    clearInterval(timerRef.current);
    const elapsed = Math.round((Date.now() - startedAt) / 1000);
    let score = 0, correct = 0, wrong = 0, unanswered = 0;
    questions.forEach((q, i) => {
      const ua = answers[i];
      if (!ua)          { unanswered++; }
      else if (ua===q.ans){ correct++; score += 2; }
      else              { wrong++;    score -= 0.5; }
    });
    score = Math.max(0, Math.round(score * 10) / 10);
    const accuracy = Math.round((correct / questions.length) * 100);
    const result   = { score, correct, wrong, unanswered, accuracy, timeTaken: elapsed };
    setMyResult(result);
    if (myGroup) submitGroupResult(myGroup.id, result);
    addResult({ title: `Group Mock (${myGroup?.members?.length || "?"} players)`, isMock: true, ...result });
    setPhase("waiting");
  }

  const timerPct   = timeLeft / TOTAL_SECS * 100;
  const timerColor = timerPct > 50 ? "#4ade80" : timerPct > 20 ? "#fbbf24" : "#f87171";

  /* ════════════════════════════════════════════════════════════════
     LOSER POPUP
  ════════════════════════════════════════════════════════════════ */
  function LoserPopup() {
    if (!loserData) return null;
    return (
      <div style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.92)", zIndex:3000, display:"flex", alignItems:"center", justifyContent:"center", padding:20 }}>
        <div style={{ background: darkMode ? "#0e0e1c" : "#fff", border:"2px solid rgba(239,68,68,0.45)", borderRadius:24, padding:"40px 36px", maxWidth:440, width:"100%", textAlign:"center", position:"relative" }}>
          <div style={{ fontSize:72, marginBottom:10 }}>💔</div>
          <div style={{ fontSize:20, fontWeight:900, color:"#f87171", marginBottom:6 }}>
            {loserData.isMe ? "You Finished Last!" : `${loserData.name} Finished Last!`}
          </div>
          <div style={{ fontSize:32, fontWeight:900, lineHeight:1.35, margin:"18px 0", background:"linear-gradient(135deg,#f87171,#fbbf24,#4ade80)", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>
            "Every winner was once a loser."
          </div>
          <div style={{ fontSize:14, color:sub, marginBottom:28, lineHeight:1.7 }}>
            {loserData.isMe
              ? "Don't quit. Every expert was once a beginner. Keep practising! 💪🔥"
              : `Keep encouraging ${loserData.name} — every loss is a lesson! 💪`}
          </div>
          <button onClick={() => setLoserData(null)} style={{ ...Btn("primary"), width:"100%", padding:"13px" }}>
            See Full Results →
          </button>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════════════════
     PHASE: RUNNING
  ════════════════════════════════════════════════════════════════ */
  if (phase === "running" && questions.length > 0) {
    const q        = questions[curr];
    const userAns  = answers[curr];
    const answered = Object.keys(answers).length;

    return (
      <div>
        <LoserPopup />
        <div style={{ display:"grid", gridTemplateColumns:"1fr 220px", gap:14, alignItems:"start" }}>

          {/* ── left: question ── */}
          <div>
            {/* status bar */}
            <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:11, padding:"10px 16px", marginBottom:12, display:"flex", alignItems:"center", justifyContent:"space-between", flexWrap:"wrap", gap:8 }}>
              <span style={{ padding:"4px 12px", borderRadius:20, background:"rgba(79,142,247,0.12)", border:"1px solid rgba(79,142,247,0.25)", fontSize:11, fontWeight:800, color:"#7aadff" }}>👥 GROUP MOCK · Q{curr+1}/{questions.length}</span>
              <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                <div style={{ width:100, height:5, background:darkMode?"rgba(255,255,255,0.06)":"#eee", borderRadius:3, overflow:"hidden" }}>
                  <div style={{ height:"100%", width:`${timerPct}%`, background:`linear-gradient(90deg,${timerColor},${timerColor}88)`, transition:"width 1s linear" }}/>
                </div>
                <span style={{ fontFamily:"'JetBrains Mono',monospace", fontWeight:900, color:timerColor, fontSize:18, minWidth:68 }}>{fmt(timeLeft)}</span>
              </div>
              <span style={{ fontSize:12, color:sub }}>{answered}/{questions.length} answered</span>
            </div>

            {/* question card */}
            <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:"22px 24px", marginBottom:12 }}>
              <div style={{ display:"flex", gap:8, marginBottom:14, flexWrap:"wrap" }}>
                <span style={{ padding:"3px 10px", borderRadius:20, fontSize:11, fontWeight:700, background:"rgba(79,142,247,0.12)", color:"#7aadff", border:"1px solid rgba(79,142,247,0.2)" }}>{q.subject}</span>
                <span style={{ padding:"3px 10px", borderRadius:20, fontSize:11, background:darkMode?"rgba(255,255,255,0.05)":"#f3f4f6", color:sub }}>{q.chapter}</span>
              </div>
              <div style={{ fontSize:16, fontWeight:600, color:txt, lineHeight:1.75, marginBottom:22 }}>{q.q}</div>

              {q.opts.map((opt, i) => {
                const sel = userAns === opt;
                return (
                  <button key={opt} onClick={() => setAnswers(a => ({ ...a, [curr]: opt }))}
                    style={{ display:"flex", alignItems:"center", gap:12, width:"100%", textAlign:"left", padding:"13px 16px", borderRadius:10, border:`1.5px solid ${sel?"#4f8ef7":"rgba(255,255,255,0.08)"}`, background:sel?"rgba(79,142,247,0.13)":darkMode?"rgba(255,255,255,0.02)":"#f9fafb", color:sel?"#7aadff":darkMode?"#ccc":"#444", cursor:"pointer", fontSize:14, fontWeight:sel?700:400, marginBottom:8, fontFamily:"inherit", transition:"all 0.15s" }}>
                    <span style={{ width:28, height:28, borderRadius:"50%", background:sel?"#4f8ef722":darkMode?"rgba(255,255,255,0.07)":"#eee", border:`1.5px solid ${sel?"#4f8ef7":"transparent"}`, display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:800, flexShrink:0, color:sel?"#4f8ef7":sub }}>
                      {["A","B","C","D"][i]}
                    </span>
                    {opt}
                  </button>
                );
              })}
            </div>

            <div style={{ display:"flex", gap:10 }}>
              <button style={Btn("ghost")} onClick={() => setCurr(c => Math.max(0, c-1))} disabled={curr===0}>← Prev</button>
              <button style={Btn("ghost")} onClick={() => setCurr(c => Math.min(questions.length-1, c+1))} disabled={curr===questions.length-1}>Next →</button>
              <div style={{ flex:1 }}/>
              <button style={Btn("danger")} onClick={() => { if (window.confirm("Submit your test? You cannot change answers after this.")) doSubmit(); }}>
                Submit Test
              </button>
            </div>
          </div>

          {/* ── right: players + palette ── */}
          <div style={{ display:"flex", flexDirection:"column", gap:12 }}>

            {/* Players */}
            <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:12, padding:14 }}>
              <div style={{ fontSize:12, fontWeight:800, color:sub, marginBottom:10, textTransform:"uppercase", letterSpacing:"0.05em" }}>👥 Players</div>
              {myGroup?.members.map(id => {
                const u    = id === user.id ? user : users.find(x => x.id === id);
                const done = myGroup?.results?.[id];
                return (
                  <div key={id} style={{ display:"flex", alignItems:"center", gap:8, padding:"8px 0", borderBottom:`1px solid ${cardBr}` }}>
                    <div style={{ width:30, height:30, borderRadius:"50%", background:"linear-gradient(135deg,#4f8ef7,#a855f7)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:800, color:"#fff", flexShrink:0 }}>
                      {u?.name?.[0] || "?"}
                    </div>
                    <div style={{ flex:1 }}>
                      <div style={{ fontSize:12, fontWeight:id===user.id?800:500, color:id===user.id?"#7aadff":txt }}>
                        {u?.name || "Unknown"}{id===user.id?" (You)":""}
                      </div>
                    </div>
                    <span style={{ fontSize:20 }}>{done ? "✅" : "⏳"}</span>
                  </div>
                );
              })}
            </div>

            {/* Palette */}
            <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:12, padding:14 }}>
              <div style={{ fontSize:12, fontWeight:800, color:sub, marginBottom:10, textTransform:"uppercase", letterSpacing:"0.05em" }}>Question Palette</div>
              <div style={{ display:"flex", flexWrap:"wrap", gap:4, marginBottom:10 }}>
                {questions.map((_, i) => {
                  const done   = answers[i] !== undefined;
                  const active = i === curr;
                  return (
                    <button key={i} onClick={() => setCurr(i)}
                      style={{ width:28, height:28, borderRadius:5, border:`1.5px solid ${active?"#4f8ef7":done?"rgba(79,142,247,0.4)":darkMode?"rgba(255,255,255,0.08)":"#e5e7eb"}`, background:active?"#4f8ef7":done?"rgba(79,142,247,0.18)":darkMode?"rgba(255,255,255,0.03)":"#f9fafb", color:active?"#fff":done?"#7aadff":sub, fontSize:10, fontWeight:600, cursor:"pointer", fontFamily:"inherit", transition:"all 0.1s" }}>
                      {i+1}
                    </button>
                  );
                })}
              </div>
              <div style={{ fontSize:11, color:sub }}>Done: <b style={{ color:"#4ade80" }}>{answered}</b> &nbsp;|&nbsp; Left: <b style={{ color:"#f87171" }}>{questions.length-answered}</b></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════════════════
     PHASE: WAITING (I submitted, waiting for others)
  ════════════════════════════════════════════════════════════════ */
  if (phase === "waiting") {
    const submitted = Object.keys(myGroup?.results || {}).length;
    const total     = myGroup?.members?.length || 0;
    return (
      <div style={{ display:"flex", alignItems:"center", justifyContent:"center", minHeight:"65vh" }}>
        <LoserPopup />
        <div style={{ textAlign:"center", maxWidth:460, width:"100%" }}>
          <div style={{ fontSize:64, marginBottom:12 }}>⏳</div>
          <div style={{ fontSize:22, fontWeight:900, color:txt, marginBottom:6 }}>Submitted! Waiting…</div>
          <div style={{ color:sub, fontSize:13, marginBottom:24 }}>Your answers are saved. Waiting for other players to finish.</div>

          <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:16, padding:22, marginBottom:16 }}>
            <div style={{ fontSize:14, fontWeight:800, color:txt, marginBottom:14 }}>Submission Status</div>
            {myGroup?.members.map(id => {
              const u    = id === user.id ? user : users.find(x => x.id === id);
              const done = myGroup?.results?.[id];
              return (
                <div key={id} style={{ display:"flex", alignItems:"center", gap:12, padding:"12px 0", borderBottom:`1px solid ${cardBr}` }}>
                  <div style={{ width:38, height:38, borderRadius:"50%", background:"linear-gradient(135deg,#4f8ef7,#a855f7)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:15, fontWeight:800, color:"#fff", flexShrink:0 }}>
                    {u?.name?.[0] || "?"}
                  </div>
                  <div style={{ flex:1, textAlign:"left" }}>
                    <div style={{ fontSize:13, fontWeight:id===user.id?800:500, color:id===user.id?"#7aadff":txt }}>
                      {u?.name || "Unknown"}{id===user.id?" (You)":""}
                    </div>
                    {done && <div style={{ fontSize:11, color:"#4ade80" }}>{myGroup.results[id].score} marks · {myGroup.results[id].accuracy}% accuracy</div>}
                  </div>
                  <div style={{ fontSize:28 }}>{done ? "✅" : "⏳"}</div>
                </div>
              );
            })}
          </div>

          <div style={{ fontSize:13, color:"#4f8ef7", fontWeight:700 }}>{submitted}/{total} submitted · Results appear when all finish</div>
          <div style={{ width:`${(submitted/total)*100}%`, height:4, background:"linear-gradient(90deg,#4f8ef7,#a855f7)", borderRadius:4, margin:"12px auto 0", transition:"width 0.5s" }}/>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════════════════
     PHASE: DONE — RESULTS
  ════════════════════════════════════════════════════════════════ */
  if (phase === "done" && myGroup) {
    const medals = ["🥇","🥈","🥉","💔"];
    const ranked = myGroup.members
      .map(id => {
        const u = id === user.id ? user : (users.find(x => x.id === id) || { name:"Unknown", profile:{} });
        const r = myGroup.results[id] || {};
        return { id, name:u.name, branch:u.profile?.branch||"—", score:r.score||0, correct:r.correct||0, wrong:r.wrong||0, unanswered:r.unanswered||0, accuracy:r.accuracy||0, time:r.timeTaken||0 };
      })
      .sort((a, b) => b.score - a.score);

    return (
      <div>
        <LoserPopup />

        {/* Hero */}
        <div style={{ textAlign:"center", marginBottom:30 }}>
          <div style={{ fontSize:60, marginBottom:8 }}>🏆</div>
          <div style={{ fontSize:26, fontWeight:900, color:txt }}>Group Mock Results</div>
          <div style={{ color:sub, fontSize:13, marginTop:4 }}>DDCET Group Mock · {new Date().toLocaleDateString("en-IN")} · {ranked.length} Players</div>
        </div>

        {/* Podium cards */}
        <div style={{ display:"flex", justifyContent:"center", gap:12, marginBottom:28, flexWrap:"wrap" }}>
          {ranked.map((m, i) => {
            const isLoser = i === ranked.length - 1 && ranked.length > 1;
            const isWinner = i === 0;
            return (
              <div key={m.id} style={{ background: isWinner ? "linear-gradient(135deg,rgba(251,191,36,0.2),rgba(251,191,36,0.04))" : isLoser ? "linear-gradient(135deg,rgba(239,68,68,0.12),transparent)" : cardBg, border:`2px solid ${isWinner?"#fbbf24":isLoser?"rgba(239,68,68,0.4)":i===1?"#9ca3af":"rgba(205,124,46,0.5)"}`, borderRadius:18, padding:"24px 20px", textAlign:"center", minWidth:160, flex:"1 1 140px", maxWidth:200, position:"relative" }}>
                <div style={{ fontSize:40, marginBottom:8 }}>{medals[i] || "🏅"}</div>
                <div style={{ width:50, height:50, borderRadius:"50%", background:`linear-gradient(135deg,hsl(${i*80}deg,70%,55%),hsl(${i*80+60}deg,65%,40%))`, display:"flex", alignItems:"center", justifyContent:"center", fontSize:20, fontWeight:900, color:"#fff", margin:"0 auto 10px" }}>
                  {m.name[0]}
                </div>
                <div style={{ fontWeight:900, fontSize:15, color:isLoser?"#f87171":isWinner?"#fbbf24":txt, marginBottom:3 }}>{m.name}</div>
                <div style={{ fontSize:11, color:sub, marginBottom:10 }}>{m.branch}</div>
                <div style={{ fontSize:30, fontWeight:900, color:isLoser?"#f87171":isWinner?"#fbbf24":"#4f8ef7", lineHeight:1 }}>{m.score}</div>
                <div style={{ fontSize:10, color:sub, marginBottom:6 }}>/ 200 marks</div>
                <div style={{ fontSize:12, fontWeight:700, color:m.accuracy>=60?"#4ade80":"#f87171" }}>{m.accuracy}% acc</div>
                {isLoser && <div style={{ marginTop:10, fontSize:11, color:"#f87171", fontStyle:"italic", lineHeight:1.4 }}>"Every winner was<br/>once a loser" 💪</div>}
                {m.id === user.id && <div style={{ position:"absolute", top:8, right:8, fontSize:9, padding:"2px 6px", borderRadius:8, background:"rgba(79,142,247,0.2)", color:"#7aadff", fontWeight:800 }}>YOU</div>}
              </div>
            );
          })}
        </div>

        {/* Full comparison table */}
        <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:16, padding:22, marginBottom:20 }}>
          <div style={{ fontSize:16, fontWeight:800, color:txt, marginBottom:16 }}>📊 Full Comparison</div>

          {/* header */}
          <div style={{ display:"grid", gridTemplateColumns:"2fr 70px 75px 70px 90px 75px", gap:6, padding:"9px 12px", background:darkMode?"rgba(255,255,255,0.05)":"#f5f5f5", borderRadius:9, marginBottom:6, fontSize:11, color:sub, fontWeight:800, textTransform:"uppercase", letterSpacing:"0.04em" }}>
            <span>Player</span><span>Score</span><span>Correct</span><span>Wrong</span><span>Accuracy</span><span>Time</span>
          </div>

          {ranked.map((m, i) => {
            const isLoser  = i === ranked.length - 1 && ranked.length > 1;
            const isWinner = i === 0;
            return (
              <div key={m.id} style={{ display:"grid", gridTemplateColumns:"2fr 70px 75px 70px 90px 75px", gap:6, padding:"13px 12px", borderBottom:`1px solid ${darkMode?"rgba(255,255,255,0.04)":"#f0f0f0"}`, alignItems:"center", background:m.id===user.id?darkMode?"rgba(79,142,247,0.07)":"rgba(79,142,247,0.04)":"transparent" }}>
                <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                  <span style={{ fontSize:18 }}>{medals[i] || "🏅"}</span>
                  <div>
                    <div style={{ fontSize:13, fontWeight:m.id===user.id?900:500, color:isWinner?"#fbbf24":isLoser?"#f87171":m.id===user.id?"#7aadff":txt }}>
                      {m.name}{m.id===user.id?" (You)":""}
                    </div>
                    <div style={{ fontSize:10, color:sub }}>{m.branch}</div>
                  </div>
                </div>
                <span style={{ fontSize:16, fontWeight:900, color:isWinner?"#fbbf24":isLoser?"#f87171":"#4f8ef7" }}>{m.score}</span>
                <span style={{ fontSize:13, fontWeight:700, color:"#4ade80" }}>{m.correct}</span>
                <span style={{ fontSize:13, fontWeight:700, color:"#f87171" }}>{m.wrong}</span>
                <div>
                  <span style={{ fontSize:13, fontWeight:700, color:m.accuracy>=60?"#4ade80":"#f87171" }}>{m.accuracy}%</span>
                  <div style={{ height:3, background:darkMode?"rgba(255,255,255,0.06)":"#eee", borderRadius:2, marginTop:3, overflow:"hidden" }}>
                    <div style={{ height:"100%", width:`${m.accuracy}%`, background:`linear-gradient(90deg,${m.accuracy>=60?"#4ade80":"#f87171"},transparent)`, borderRadius:2 }}/>
                  </div>
                </div>
                <span style={{ fontSize:11, color:sub, fontFamily:"'JetBrains Mono',monospace" }}>{Math.floor(m.time/60)}m{m.time%60}s</span>
              </div>
            );
          })}
        </div>

        <div style={{ display:"flex", gap:12, flexWrap:"wrap" }}>
          <button style={Btn("primary")} onClick={() => printGroupPDF(myGroup, users, user)}>⬇ Download Group PDF</button>
          <button style={Btn("ghost")} onClick={() => { setPhase("lobby"); setMyResult(null); setLoserData(null); }}>← Back to Lobby</button>
        </div>
      </div>
    );
  }

  /* ════════════════════════════════════════════════════════════════
     PHASE: LOBBY
  ════════════════════════════════════════════════════════════════ */
  return (
    <div>
      <div style={{ fontSize:22, fontWeight:900, color:txt, marginBottom:4 }}>Group Mock Test</div>
      <div style={{ color:sub, fontSize:13, marginBottom:20 }}>
        Challenge up to 3 friends. Everyone gets the same questions at the same time. May the best student win! 🏆
      </div>

      {/* ── Pending invites FOR ME ── */}
      {pendingInvites.length > 0 && (
        <div style={{ background:"rgba(79,142,247,0.07)", border:"2px solid rgba(79,142,247,0.35)", borderRadius:14, padding:20, marginBottom:22 }}>
          <div style={{ fontSize:15, fontWeight:900, color:"#7aadff", marginBottom:14 }}>
            📨 Group Mock Invites ({pendingInvites.length})
          </div>
          {pendingInvites.map(inv => {
            const host = users.find(u => u.id === inv.from);
            const grp  = groups.find(g => g.id === inv.groupId);
            return (
              <div key={inv.id} style={{ display:"flex", alignItems:"center", gap:12, padding:"14px 0", borderBottom:`1px solid rgba(79,142,247,0.12)` }}>
                <div style={{ width:44, height:44, borderRadius:"50%", background:"linear-gradient(135deg,#4f8ef7,#a855f7)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:17, fontWeight:800, color:"#fff", flexShrink:0 }}>
                  {host?.name?.[0] || "?"}
                </div>
                <div style={{ flex:1 }}>
                  <div style={{ fontWeight:800, color:txt, fontSize:14 }}>
                    <span style={{ color:"#7aadff" }}>{host?.name || "Someone"}</span> invited you to a Group Mock!
                  </div>
                  <div style={{ fontSize:11, color:sub, marginTop:2 }}>
                    {grp?.members?.length || 1} player(s) in session · 100 Qs · 120 min · DDCET pattern
                  </div>
                </div>
                <button onClick={() => acceptGroupInvite(inv.id)}
                  style={{ ...Btn("green"), padding:"8px 16px", fontSize:12, marginRight:6 }}>
                  ✓ Join Session
                </button>
                <button onClick={() => rejectGroupInvite(inv.id)}
                  style={{ ...Btn("danger"), padding:"8px 14px", fontSize:12 }}>
                  ✕
                </button>
              </div>
            );
          })}
        </div>
      )}

      {/* ── My Active Session ── */}
      {myGroup ? (
        <div style={{ background:cardBg, border:"2px solid rgba(79,142,247,0.35)", borderRadius:16, padding:24 }}>

          {/* Session header */}
          <div style={{ display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:20, gap:12, flexWrap:"wrap" }}>
            <div>
              <div style={{ fontSize:17, fontWeight:900, color:txt }}>
                {myGroup.host === user.id ? "🎮 Your Session" : "🎮 Active Session"}
              </div>
              <div style={{ fontSize:12, color:sub, marginTop:3 }}>
                Status: <b style={{ color: myGroup.status==="lobby"?"#fbbf24":myGroup.status==="running"?"#4ade80":"#4f8ef7", textTransform:"uppercase" }}>{myGroup.status}</b>
                &nbsp;·&nbsp; {myGroup.members.length}/4 players
              </div>
            </div>
            {myGroup.host === user.id && myGroup.status === "lobby" && (
              <button
                onClick={() => {
                  if (myGroup.members.length < 2) { alert("You need at least 1 friend to join before starting!"); return; }
                  startGroupSession(myGroup.id);
                }}
                style={{ ...Btn("green"), opacity: myGroup.members.length >= 2 ? 1 : 0.5 }}>
                🚀 Start Test for Everyone
              </button>
            )}
          </div>

          {/* Members grid */}
          <div style={{ marginBottom:20 }}>
            <div style={{ fontSize:12, fontWeight:800, color:sub, marginBottom:10, textTransform:"uppercase", letterSpacing:"0.04em" }}>Players in Session</div>
            <div style={{ display:"flex", flexWrap:"wrap", gap:8 }}>
              {myGroup.members.map(id => {
                const u = id === user.id ? user : users.find(x => x.id === id);
                return (
                  <div key={id} style={{ display:"flex", alignItems:"center", gap:8, padding:"10px 14px", background:id===user.id?"rgba(79,142,247,0.12)":darkMode?"rgba(255,255,255,0.04)":"#f9fafb", borderRadius:10, border:`1.5px solid ${id===user.id?"rgba(79,142,247,0.35)":cardBr}` }}>
                    <div style={{ width:32, height:32, borderRadius:"50%", background:"linear-gradient(135deg,#4f8ef7,#a855f7)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:13, fontWeight:800, color:"#fff", flexShrink:0 }}>
                      {u?.name?.[0] || "?"}
                    </div>
                    <div>
                      <div style={{ fontSize:12, fontWeight:700, color:id===user.id?"#7aadff":txt }}>{u?.name || "Unknown"}</div>
                      {id === myGroup.host && <div style={{ fontSize:9, color:"#fbbf24", fontWeight:800 }}>HOST</div>}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* ── Invite Panel (host only, lobby only, < 4 members) ── */}
          {myGroup.host === user.id && myGroup.status === "lobby" && myGroup.members.length < 4 && (
            <div style={{ borderTop:`1px solid ${cardBr}`, paddingTop:18 }}>
              <div style={{ fontSize:14, fontWeight:900, color:txt, marginBottom:4 }}>
                👥 Invite Friends &nbsp;
                <span style={{ fontSize:12, color:sub, fontWeight:400 }}>({myGroup.members.length}/4 slots filled — need {4 - myGroup.members.length} more max)</span>
              </div>
              <div style={{ fontSize:12, color:sub, marginBottom:14 }}>
                These are people who follow you or you follow them.
              </div>

              {connections.length === 0 ? (
                <div style={{ padding:"18px", background:darkMode?"rgba(255,255,255,0.03)":"#f9fafb", borderRadius:10, fontSize:13, color:sub, textAlign:"center" }}>
                  No connections yet. Go to <b style={{ color:"#4f8ef7" }}>Explore Students</b> and send follow requests first.
                </div>
              ) : (
                <div style={{ display:"flex", flexDirection:"column", gap:8 }}>
                  {connections
                    .filter(c => !myGroup.members.includes(c.id))
                    .map(c => {
                      const alreadyInvited = invites.some(i => i.groupId === myGroup.id && i.to === c.id && i.status === "pending");
                      const accepted       = invites.some(i => i.groupId === myGroup.id && i.to === c.id && i.status === "accepted");
                      return (
                        <div key={c.id} style={{ display:"flex", alignItems:"center", gap:12, padding:"12px 16px", background:darkMode?"rgba(255,255,255,0.03)":"#f9fafb", borderRadius:11, border:`1px solid ${cardBr}` }}>
                          <div style={{ width:38, height:38, borderRadius:"50%", background:"linear-gradient(135deg,#a855f7,#6366f1)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:15, fontWeight:800, color:"#fff", flexShrink:0 }}>
                            {c.name[0]}
                          </div>
                          <div style={{ flex:1 }}>
                            <div style={{ fontSize:14, fontWeight:800, color:txt }}>{c.name}</div>
                            <div style={{ fontSize:11, color:sub }}>@{c.socialProfile?.username||"—"} · {c.profile?.branch}</div>
                          </div>
                          <button
                            disabled={alreadyInvited || accepted}
                            onClick={() => sendGroupInvite(myGroup.id, c.id)}
                            style={{ padding:"8px 18px", borderRadius:9, border:"none", cursor:alreadyInvited||accepted?"default":"pointer", background:accepted?"rgba(74,222,128,0.15)":alreadyInvited?"rgba(251,191,36,0.15)":"linear-gradient(135deg,#4f8ef7,#a855f7)", color:accepted?"#4ade80":alreadyInvited?"#fbbf24":"#fff", fontSize:12, fontWeight:800, fontFamily:"inherit" }}>
                            {accepted ? "✓ Joined" : alreadyInvited ? "⏳ Invited" : "Invite →"}
                          </button>
                        </div>
                      );
                    })
                  }
                </div>
              )}

              {myGroup.members.length < 2 && (
                <div style={{ marginTop:14, padding:"11px 16px", background:"rgba(251,191,36,0.08)", border:"1.5px solid rgba(251,191,36,0.3)", borderRadius:10, fontSize:12, color:"#fbbf24", fontWeight:600 }}>
                  ⚠️ Invite at least 1 friend and wait for them to accept before starting the test.
                </div>
              )}
            </div>
          )}

          {/* Non-host waiting message */}
          {myGroup.host !== user.id && myGroup.status === "lobby" && (
            <div style={{ marginTop:4, padding:"14px 16px", background:"rgba(79,142,247,0.07)", border:"1px solid rgba(79,142,247,0.2)", borderRadius:10, fontSize:13, color:"#7aadff", fontWeight:600 }}>
              ⏳ Waiting for the host to start the test. Get ready!
            </div>
          )}
        </div>

      ) : (
        /* ── No active session: Create button + info ── */
        <>
          <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))", gap:12, marginBottom:24 }}>
            {[
              { icon:"👥", t:"2–4 Players",    d:"Max 4 per session"      },
              { icon:"📝", t:"100 Questions",  d:"Real DDCET pattern"     },
              { icon:"⏱",  t:"120 Minutes",   d:"Same as actual exam"    },
              { icon:"📊", t:"Live Comparison",d:"All results ranked"     },
              { icon:"📄", t:"Group PDF",      d:"Download after results" },
              { icon:"🏆", t:"Ranked Results", d:"1st to last place"      },
            ].map(c => (
              <div key={c.t} style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:12, padding:"18px 16px", textAlign:"center" }}>
                <div style={{ fontSize:28, marginBottom:8 }}>{c.icon}</div>
                <div style={{ fontWeight:800, color:txt, fontSize:13 }}>{c.t}</div>
                <div style={{ fontSize:11, color:sub, marginTop:3 }}>{c.d}</div>
              </div>
            ))}
          </div>

          <button onClick={() => createGroup()} style={{ ...Btn("primary"), padding:"14px 36px", fontSize:15 }}>
            🚀 Create Group Session
          </button>
          <div style={{ fontSize:12, color:sub, marginTop:10 }}>
            After creating, invite friends from your connections list.
          </div>
        </>
      )}
    </div>
  );
}
