import { useState, useEffect, useRef } from "react";
import { QUESTION_BANK, shuffle } from "../data/subjects";
import { useApp } from "../context/AppContext";

function downloadGroupPDF(session, users, user) {
  const members = session.members.map(id => {
    const u = users.find(x => x.id === id) || { name: id === user.id ? user.name : "Unknown", profile:{} };
    const r = session.results[id] || {};
    return { name: u.name, branch: u.profile?.branch||"—", score: r.score||0, correct: r.correct||0, wrong: r.wrong||0, accuracy: r.accuracy||0, time: r.timeTaken||0 };
  });

  const best = [...members].sort((a,b)=>b.score-a.score)[0];

  const html = `<!DOCTYPE html>
<html><head><title>Ranklify Group Mock Result</title>
<style>
  body{font-family:Arial,sans-serif;padding:32px;color:#222;max-width:900px;margin:0 auto}
  h1{color:#4f8ef7;font-size:20px}h2{font-size:14px;color:#444;margin-top:20px}
  table{width:100%;border-collapse:collapse;font-size:12px;margin-top:8px}
  th{background:linear-gradient(135deg,#4f8ef7,#a855f7);color:#fff;padding:10px 12px;text-align:left}
  td{padding:10px 12px;border-bottom:1px solid #eee}
  tr:nth-child(even) td{background:#f9f9f9}
  .winner{background:rgba(251,191,36,0.1)!important;border-left:3px solid #fbbf24}
  .logo{font-size:24px;font-weight:900;color:#4f8ef7}
  .badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px}
  .rank1{background:#fef9c3;color:#a16207}
  .rank2{background:#f3f4f6;color:#374151}
  .rank3{background:#fef3c7;color:#92400e}
</style></head><body>
<div class="logo">⚡ Ranklify</div>
<p style="color:#888;font-size:11px">DDCET Rank Booster — Group Mock Test</p>
<h1>Group Mock Test Results</h1>
<p style="font-size:12px;color:#666">Date: ${new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})} | Participants: ${members.length} | Questions: ${session.totalQ||100} | Time: ${session.testTime||120} min</p>
<h2>🏆 Winner: ${best.name} with ${best.score} marks (${best.accuracy}% accuracy)</h2>
<table><thead><tr><th>Rank</th><th>Name</th><th>Branch</th><th>Score /200</th><th>Correct</th><th>Wrong</th><th>Accuracy</th><th>Time</th></tr></thead><tbody>
${[...members].sort((a,b)=>b.score-a.score).map((m,i)=>`
<tr class="${i===0?"winner":""}">
  <td><span class="badge ${i===0?"rank1":i===1?"rank2":"rank3"}">${i===0?"🥇":i===1?"🥈":"🥉"} #${i+1}</span></td>
  <td><b>${m.name}</b></td>
  <td>${m.branch}</td>
  <td style="color:#4f8ef7;font-weight:800">${m.score}</td>
  <td style="color:#16a34a">${m.correct}</td>
  <td style="color:#dc2626">${m.wrong}</td>
  <td>${m.accuracy}%</td>
  <td>${Math.floor(m.time/60)}m${m.time%60}s</td>
</tr>`).join("")}
</tbody></table>
<p style="margin-top:28px;color:#aaa;font-size:10px;text-align:center">Generated by Ranklify · DDCET Rank Booster · Same Pattern. Same Time. Same Marking.</p>
</body></html>`;

  const w = window.open("","_blank");
  w.document.write(html); w.document.close(); w.print();
}

const MOCK_TIME = 120 * 60;

export default function GroupMock() {
  const { user, users, darkMode, myFollowing, createGroup, groups, joinGroup, submitGroupResult, addResult } = useApp();

  const following   = myFollowing ? myFollowing() : [];
  const [tab, setTab] = useState("create"); // create | join | result
  const [selectedMembers, setSelectedMembers] = useState([]);
  const [mySession, setMySession]   = useState(null);
  const [phase, setPhase]           = useState("lobby"); // lobby | running | done
  const [questions, setQuestions]   = useState([]);
  const [answers,   setAnswers]     = useState({});
  const [curr, setCurr]             = useState(0);
  const [timeLeft,  setTimeLeft]    = useState(MOCK_TIME);
  const [myResult,  setMyResult]    = useState(null);
  const [startedAt, setStartedAt]   = useState(null);
  const timerRef = useRef(null);

  const txt    = darkMode ? "#e2e2f0" : "#111";
  const sub    = darkMode ? "#666"    : "#888";
  const cardBg = darkMode ? "rgba(255,255,255,0.03)"  : "#fff";
  const cardBr = darkMode ? "rgba(255,255,255,0.07)"  : "#e5e7eb";
  const btn    = (v="primary") => ({ padding:"10px 20px", borderRadius:9, border:"none", cursor:"pointer", fontSize:13, fontWeight:600, fontFamily:"inherit",
    background: v==="primary"?"linear-gradient(135deg,#4f8ef7,#a855f7)":v==="danger"?"rgba(239,68,68,0.15)":darkMode?"rgba(255,255,255,0.06)":"#f3f4f6",
    color: v==="primary"?"#fff":v==="danger"?"#f87171":txt });

  // Available sessions to join
  const joinableSessions = groups.filter(g =>
    g.status === "waiting" &&
    g.host !== user?.id &&
    !g.members.includes(user?.id) &&
    g.members.length < 4
  );

  // Timer
  useEffect(() => {
    if (phase !== "running") return;
    timerRef.current = setInterval(() => {
      setTimeLeft(t => {
        if (t <= 1) { clearInterval(timerRef.current); submitTest(true); return 0; }
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(timerRef.current);
  }, [phase]);

  function createSession() {
    if (selectedMembers.length === 0) return;
    const allMembers = [user.id, ...selectedMembers];
    const g = createGroup(allMembers);
    setMySession({ ...g, totalQ:100, testTime:120 });
    setPhase("lobby");
  }

  function startSession() {
    const base = shuffle([...QUESTION_BANK]);
    let pool = [...base];
    while (pool.length < 100) pool = [...pool, ...base];
    setQuestions(pool.slice(0, 100));
    setAnswers({}); setCurr(0);
    setTimeLeft(MOCK_TIME); setStartedAt(Date.now());
    setPhase("running");
  }

  function submitTest(auto = false) {
    clearInterval(timerRef.current);
    const timeTaken = Math.round((Date.now() - startedAt) / 1000);
    const scored    = questions.map((q, i) => ({ ...q, userAns: answers[i] }));
    let score = 0, correct = 0, wrong = 0, unanswered = 0;
    scored.forEach(q => {
      if (!q.userAns)             { unanswered++; }
      else if (q.userAns===q.ans) { correct++; score += 2; }
      else                        { wrong++;   score -= 0.5; }
    });
    score = Math.max(0, Math.round(score*10)/10);
    const accuracy = Math.round(correct/questions.length*100);
    const result   = { score, correct, wrong, unanswered, accuracy, timeTaken, scored };
    setMyResult(result);
    if (mySession) {
      submitGroupResult(mySession.id, result);
      setMySession(prev => ({ ...prev, results: { ...(prev?.results||{}), [user.id]: result } }));
    }
    addResult({ title:"Group Mock Test", isMock:true, ...result });
    setPhase("done");
  }

  function fmt(s) { const m=Math.floor(s/60),sc=s%60; return `${String(m).padStart(2,"0")}:${String(sc).padStart(2,"0")}`; }
  const timerPct = timeLeft/MOCK_TIME*100;
  const timerColor = timerPct>50?"#4ade80":timerPct>20?"#fbbf24":"#f87171";

  // ── RUNNING ──
  if (phase === "running") {
    const q = questions[curr];
    const userAns = answers[curr];
    const answered = Object.keys(answers).length;
    return (
      <div style={{ display:"grid", gridTemplateColumns:"1fr 210px", gap:16 }}>
        <div>
          <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:12, padding:"11px 16px", marginBottom:12, display:"flex", alignItems:"center", justifyContent:"space-between", gap:12, flexWrap:"wrap" }}>
            <span style={{ fontSize:13, color:sub }}>👥 Group Mock · Q{curr+1}/{questions.length}</span>
            <div style={{ display:"flex", alignItems:"center", gap:8 }}>
              <div style={{ width:110, height:5, background:darkMode?"rgba(255,255,255,0.06)":"#eee", borderRadius:3, overflow:"hidden" }}>
                <div style={{ height:"100%", width:`${timerPct}%`, background:`linear-gradient(90deg,${timerColor},${timerColor}99)`, transition:"width 1s linear" }}/>
              </div>
              <span style={{ fontFamily:"'JetBrains Mono',monospace", fontWeight:700, color:timerColor, fontSize:16 }}>{fmt(timeLeft)}</span>
            </div>
            <span style={{ fontSize:12, color:sub }}>{answered}/{questions.length}</span>
          </div>

          <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:24, marginBottom:12 }}>
            <div style={{ display:"flex", gap:8, marginBottom:12 }}>
              <span style={{ padding:"3px 10px", borderRadius:20, fontSize:11, fontWeight:600, background:"rgba(79,142,247,0.12)", color:"#7aadff", border:"1px solid rgba(79,142,247,0.2)" }}>{q.subject}</span>
            </div>
            <div style={{ fontSize:16, fontWeight:600, color:txt, marginBottom:20, lineHeight:1.7 }}>{q.q}</div>
            {q.opts.map((opt,i)=>{
              let bg=darkMode?"rgba(255,255,255,0.03)":"#f9fafb", border=darkMode?"rgba(255,255,255,0.08)":"#e5e7eb", color=darkMode?"#ccc":"#444";
              if(userAns===opt){bg="rgba(79,142,247,0.12)";border="#4f8ef755";color="#7aadff";}
              return (
                <button key={opt} onClick={()=>setAnswers(a=>({...a,[curr]:opt}))}
                  style={{ display:"flex",alignItems:"center",gap:10,width:"100%",textAlign:"left",padding:"12px 16px",borderRadius:9,border:`1.5px solid ${border}`,background:bg,color,cursor:"pointer",fontSize:13.5,fontWeight:500,marginBottom:8,fontFamily:"inherit",transition:"all 0.15s" }}>
                  <span style={{ width:24,height:24,borderRadius:"50%",background:darkMode?"rgba(255,255,255,0.06)":"#eee",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,flexShrink:0 }}>{["A","B","C","D"][i]}</span>
                  {opt}
                </button>
              );
            })}
          </div>

          <div style={{ display:"flex", gap:10 }}>
            <button style={btn("ghost")} onClick={()=>setCurr(c=>Math.max(0,c-1))} disabled={curr===0}>← Prev</button>
            <button style={btn("ghost")} onClick={()=>setCurr(c=>Math.min(questions.length-1,c+1))} disabled={curr===questions.length-1}>Next →</button>
            <div style={{ flex:1 }}/>
            <button style={btn("danger")} onClick={()=>{if(window.confirm("Submit?"))submitTest();}}>Submit</button>
          </div>
        </div>

        <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:14 }}>
          <div style={{ fontSize:12, fontWeight:700, color:sub, marginBottom:10 }}>Question Palette</div>
          <div style={{ display:"flex", flexWrap:"wrap", gap:4, marginBottom:12 }}>
            {questions.map((_,i)=>{
              const ans=answers[i]!==undefined,active=i===curr;
              return <button key={i} onClick={()=>setCurr(i)}
                style={{ width:28,height:28,borderRadius:5,border:`1.5px solid ${active?"#4f8ef7":ans?"#4f8ef744":darkMode?"rgba(255,255,255,0.08)":"#e5e7eb"}`,background:active?"#4f8ef7":ans?"rgba(79,142,247,0.2)":darkMode?"rgba(255,255,255,0.03)":"#f9fafb",color:active||ans?"#7aadff":sub,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"inherit" }}>
                {i+1}</button>;
            })}
          </div>
          <div style={{ fontSize:11, color:sub }}>Answered: <b style={{ color:"#4f8ef7" }}>{answered}</b></div>
          <div style={{ fontSize:11, color:sub }}>Left: <b style={{ color:"#f87171" }}>{questions.length-answered}</b></div>
        </div>
      </div>
    );
  }

  // ── DONE ──
  if (phase === "done" && myResult) {
    const session = groups.find(g => g.id === mySession?.id) || mySession;
    const allDone = session && Object.keys(session.results||{}).length >= (session.members||[]).length;

    const members = (session?.members||[user.id]).map(id => {
      const u = id === user.id ? user : (users.find(x => x.id === id) || { name:"Waiting…", profile:{} });
      const r = (session?.results||{})[id] || {};
      return { id, name:u.name, branch:u.profile?.branch||"—", score:r.score||0, correct:r.correct||0, wrong:r.wrong||0, accuracy:r.accuracy||0, time:r.timeTaken||0 };
    }).sort((a,b)=>b.score-a.score);

    return (
      <div>
        <div style={{ textAlign:"center", marginBottom:24 }}>
          <div style={{ fontSize:48, marginBottom:8 }}>🏆</div>
          <div style={{ fontSize:22, fontWeight:800, color:txt }}>Group Mock Results!</div>
          <div style={{ color:sub, fontSize:13, marginTop:4 }}>DDCET Group Mock Test · {new Date().toLocaleDateString("en-IN")}</div>
        </div>

        {/* Podium */}
        <div style={{ display:"flex", justifyContent:"center", gap:12, marginBottom:24, flexWrap:"wrap" }}>
          {members.slice(0,4).map((m,i)=>( 
            <div key={m.id} style={{ background:i===0?"linear-gradient(135deg,rgba(251,191,36,0.15),rgba(251,191,36,0.05))":cardBg, border:`2px solid ${i===0?"#fbbf24":i===1?"#9ca3af":i===2?"#cd7c2e":cardBr}`, borderRadius:14, padding:"20px 18px", textAlign:"center", minWidth:150, position:"relative" }}>
              <div style={{ fontSize:28, marginBottom:6 }}>{i===0?"🥇":i===1?"🥈":i===2?"🥉":"🏅"}</div>
              <div style={{ width:44, height:44, borderRadius:"50%", background:`linear-gradient(135deg,hsl(${i*80}deg,70%,55%),hsl(${i*80+60}deg,70%,40%))`, display:"flex", alignItems:"center", justifyContent:"center", fontSize:18, fontWeight:800, color:"#fff", margin:"0 auto 8px" }}>{m.name[0]}</div>
              <div style={{ fontWeight:800, color:txt, fontSize:14 }}>{m.name}</div>
              <div style={{ fontSize:11, color:sub, marginBottom:8 }}>{m.branch}</div>
              <div style={{ fontSize:24, fontWeight:800, color:i===0?"#fbbf24":"#4f8ef7" }}>{m.score}</div>
              <div style={{ fontSize:10, color:sub }}>/ 200 marks</div>
              <div style={{ fontSize:11, color:"#4ade80", marginTop:4 }}>{m.accuracy}% accuracy</div>
              {m.id === user.id && <div style={{ position:"absolute", top:8, right:8, fontSize:9, padding:"2px 6px", borderRadius:8, background:"rgba(79,142,247,0.2)", color:"#7aadff" }}>YOU</div>}
            </div>
          ))}
        </div>

        {/* Full table */}
        <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:20, marginBottom:16 }}>
          <div style={{ fontSize:14, fontWeight:700, color:txt, marginBottom:14 }}>Full Comparison</div>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 70px 70px 70px 80px 70px", gap:8, padding:"8px 10px", background:darkMode?"rgba(255,255,255,0.04)":"#f5f5f5", borderRadius:8, marginBottom:8, fontSize:11, color:sub, fontWeight:700, textTransform:"uppercase" }}>
            <span>Name</span><span>Score</span><span>Correct</span><span>Wrong</span><span>Accuracy</span><span>Time</span>
          </div>
          {members.map((m,i)=>(
            <div key={m.id} style={{ display:"grid", gridTemplateColumns:"1fr 70px 70px 70px 80px 70px", gap:8, padding:"12px 10px", borderBottom:`1px solid ${darkMode?"rgba(255,255,255,0.04)":"#f0f0f0"}`, alignItems:"center", background:m.id===user.id?darkMode?"rgba(79,142,247,0.06)":"rgba(79,142,247,0.04)":"transparent" }}>
              <div style={{ display:"flex", alignItems:"center", gap:8 }}>
                <span style={{ fontSize:14 }}>{i===0?"🥇":i===1?"🥈":i===2?"🥉":"🏅"}</span>
                <span style={{ fontSize:13, fontWeight:m.id===user.id?700:400, color:m.id===user.id?"#7aadff":txt }}>{m.name}{m.id===user.id?" (You)":""}</span>
              </div>
              <span style={{ fontSize:14, fontWeight:700, color:"#4f8ef7" }}>{m.score}</span>
              <span style={{ fontSize:13, color:"#4ade80" }}>{m.correct}</span>
              <span style={{ fontSize:13, color:"#f87171" }}>{m.wrong}</span>
              <span style={{ fontSize:13, color:(m.accuracy||0)>=60?"#4ade80":"#f87171" }}>{m.accuracy}%</span>
              <span style={{ fontSize:11, color:sub }}>{Math.floor(m.time/60)}m{m.time%60}s</span>
            </div>
          ))}
        </div>

        <div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
          <button style={btn("primary")} onClick={()=>downloadGroupPDF(session||{members:[user.id],results:{[user.id]:myResult},totalQ:100,testTime:120}, users, user)}>
            ⬇ Download Group PDF
          </button>
          <button style={btn("ghost")} onClick={()=>{ setPhase("lobby"); setMySession(null); setTab("create"); }}>
            New Group Mock
          </button>
        </div>
      </div>
    );
  }

  // ── LOBBY / CREATE ──
  return (
    <div>
      <div style={{ fontSize:22, fontWeight:800, color:txt, marginBottom:4 }}>Group Mock Test</div>
      <div style={{ color:sub, fontSize:13, marginBottom:22 }}>Challenge 1–3 friends to a mock test. Compare results. Download group PDF.</div>

      <div style={{ display:"flex", gap:8, marginBottom:20 }}>
        {[{id:"create",l:"Create Session"},{id:"join",l:"Join Session"}].map(t=>(
          <button key={t.id} onClick={()=>setTab(t.id)} style={{ ...btn(tab===t.id?"primary":"ghost"), fontSize:13 }}>{t.l}</button>
        ))}
      </div>

      {/* ── CREATE ── */}
      {tab==="create" && (
        <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:24 }}>
          <div style={{ fontSize:15, fontWeight:700, color:txt, marginBottom:6 }}>Create Group Session</div>
          <div style={{ fontSize:12, color:sub, marginBottom:18 }}>Select 1–3 friends from your following list (max 4 total including you)</div>

          {following.length === 0 ? (
            <div style={{ padding:"20px", textAlign:"center", color:sub, fontSize:13 }}>
              You need to follow at least 1 student to start a group mock.<br/>
              <span style={{ color:"#4f8ef7" }}>Go to Explore Students → follow someone first.</span>
            </div>
          ) : (
            <>
              <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))", gap:10, marginBottom:20 }}>
                {following.slice(0,3).map(u=>{
                  const sel = selectedMembers.includes(u.id);
                  return (
                    <div key={u.id} onClick={()=>{
                      if(sel) setSelectedMembers(p=>p.filter(id=>id!==u.id));
                      else if(selectedMembers.length<3) setSelectedMembers(p=>[...p,u.id]);
                    }}
                      style={{ display:"flex", alignItems:"center", gap:10, padding:"12px 14px", borderRadius:10, border:`2px solid ${sel?"#4f8ef7":cardBr}`, background:sel?"rgba(79,142,247,0.1)":darkMode?"rgba(255,255,255,0.02)":"#f9fafb", cursor:"pointer", transition:"all 0.2s" }}>
                      <div style={{ width:36, height:36, borderRadius:"50%", background:"linear-gradient(135deg,#4f8ef7,#a855f7)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:14, fontWeight:800, color:"#fff", flexShrink:0 }}>{u.name[0]}</div>
                      <div style={{ flex:1 }}>
                        <div style={{ fontSize:13, fontWeight:600, color:txt }}>{u.name}</div>
                        <div style={{ fontSize:10, color:sub }}>{u.profile?.branch}</div>
                      </div>
                      {sel && <span style={{ color:"#4f8ef7", fontSize:18 }}>✓</span>}
                    </div>
                  );
                })}
              </div>
              <div style={{ fontSize:12, color:sub, marginBottom:16 }}>Selected: {selectedMembers.length}/3 friends · Total: {selectedMembers.length+1}/4</div>
              <div style={{ background:darkMode?"rgba(79,142,247,0.08)":"rgba(79,142,247,0.05)", border:"1px solid rgba(79,142,247,0.2)", borderRadius:10, padding:"12px 16px", marginBottom:18 }}>
                <div style={{ fontSize:12, color:"#7aadff", fontWeight:700, marginBottom:4 }}>📋 Group Mock Details</div>
                <div style={{ fontSize:12, color:sub }}>100 questions · 120 minutes · +2/−0.5 marking · Group PDF at end</div>
              </div>
              <button onClick={createSession} disabled={selectedMembers.length===0} style={{ ...btn("primary"), opacity:selectedMembers.length===0?0.5:1 }}>
                🚀 Create & Start Group Mock
              </button>
            </>
          )}
        </div>
      )}

      {/* ── JOIN ── */}
      {tab==="join" && (
        <div style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:14, padding:24 }}>
          <div style={{ fontSize:15, fontWeight:700, color:txt, marginBottom:16 }}>Available Sessions</div>
          {joinableSessions.length===0 ? (
            <div style={{ textAlign:"center", color:sub, fontSize:13, padding:"20px 0" }}>
              No open sessions right now.<br/>Ask a friend to create one!
            </div>
          ) : (
            joinableSessions.map(g=>{
              const host = users.find(u=>u.id===g.host);
              return (
                <div key={g.id} style={{ display:"flex", alignItems:"center", gap:12, padding:"14px 0", borderBottom:`1px solid ${cardBr}` }}>
                  <div style={{ flex:1 }}>
                    <div style={{ fontWeight:600, color:txt, fontSize:13 }}>Session by {host?.name||"Unknown"}</div>
                    <div style={{ fontSize:11, color:sub }}>{g.members.length}/4 joined · 100 Qs · 120 min</div>
                  </div>
                  <button onClick={()=>{ joinGroup(g.id); setMySession(g); startSession(); }}
                    style={{ ...btn("primary"), padding:"8px 18px" }}>Join →</button>
                </div>
              );
            })
          )}
        </div>
      )}

      {/* Info cards */}
      {!mySession && (
        <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))", gap:12, marginTop:20 }}>
          {[
            {icon:"👥",t:"2–4 Players",d:"Invite up to 3 friends"},
            {icon:"📝",t:"100 Questions",d:"Real DDCET pattern"},
            {icon:"⏱",t:"120 Minutes",d:"Same as real exam"},
            {icon:"📄",t:"Group PDF",d:"All results in one PDF"},
          ].map(c=>(
            <div key={c.t} style={{ background:cardBg, border:`1px solid ${cardBr}`, borderRadius:12, padding:"16px 18px", textAlign:"center" }}>
              <div style={{ fontSize:28, marginBottom:8 }}>{c.icon}</div>
              <div style={{ fontWeight:700, color:txt, fontSize:13 }}>{c.t}</div>
              <div style={{ fontSize:11, color:sub, marginTop:3 }}>{c.d}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
