/**
 * History.jsx — Ranklify
 * Three tabs: Unit Tests | Personal Mocks | Group Mocks
 * Each entry has Download PDF button with ranklify.mocktestN.pdf naming
 */
import { useState } from "react";
import { useApp } from "../context/AppContext";

/* ── PDF helpers ─────────────────────────────────────────── */
function triggerDownload(html, filename) {
  const blob = new Blob([html], {type:"text/html"});
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href=url; a.download=filename; a.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
}

function personalPDF(r, user, mockNum) {
  const html=`<!DOCTYPE html><html><head><title>ranklify.mocktest${mockNum}</title>
<style>body{font-family:Arial;padding:32px;color:#222;max-width:800px;margin:0 auto}
.logo{font-size:22px;font-weight:900;color:#4f8ef7}
h1{color:#4f8ef7;font-size:18px;margin:8px 0 4px}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}
.box{background:#f3f4f6;border-radius:8px;padding:14px;text-align:center}
.bv{font-size:24px;font-weight:800;color:#4f8ef7}.bl{font-size:11px;color:#666;margin-top:4px}
table{width:100%;border-collapse:collapse;font-size:12px;margin-top:12px}
th{background:#4f8ef7;color:#fff;padding:8px 12px;text-align:left}
td{padding:8px 12px;border-bottom:1px solid #eee}
.c{color:#16a34a}.w{color:#dc2626}
footer{margin-top:24px;color:#aaa;font-size:10px;text-align:center}
</style></head><body>
<div class="logo">⚡ Ranklify</div>
<p style="color:#888;font-size:11px">DDCET Rank Booster</p>
<h1>Personal Mock Test Result — #${mockNum}</h1>
<table style="width:auto;margin-bottom:12px;font-size:13px">
  <tr><td><b>Student</b></td><td style="padding-left:20px">${user?.name||"—"}</td></tr>
  <tr><td><b>Branch</b></td><td style="padding-left:20px">${user?.profile?.branch||"—"}</td></tr>
  <tr><td><b>Exam Type</b></td><td style="padding-left:20px">Personal Mock Test</td></tr>
  <tr><td><b>Date</b></td><td style="padding-left:20px">${r.date||new Date().toLocaleDateString("en-IN")}</td></tr>
</table>
<div class="grid">
  <div class="box"><div class="bv">${r.score}</div><div class="bl">Score /200</div></div>
  <div class="box"><div class="bv">${r.correct}</div><div class="bl">Correct (+2)</div></div>
  <div class="box"><div class="bv">${r.wrong}</div><div class="bl">Wrong (−0.5)</div></div>
  <div class="box"><div class="bv">${r.unanswered||0}</div><div class="bl">Unattempted</div></div>
  <div class="box"><div class="bv">${r.accuracy}%</div><div class="bl">Accuracy</div></div>
  <div class="box"><div class="bv">${Math.floor((r.timeTaken||0)/60)}m</div><div class="bl">Time Taken</div></div>
</div>
<footer>Generated by Ranklify · File: ranklify.mocktest${mockNum}.pdf</footer>
</body></html>`;
  triggerDownload(html, `ranklify.mocktest${mockNum}.pdf`);
}

function groupPDF(r, user, mockNum) {
  const participants = r.participants || [];
  const ranked = [...participants].sort((a,b)=>b.score-a.score);
  const rankLabels=["1st","2nd","3rd","Loser"];
  const html=`<!DOCTYPE html><html><head><title>ranklify.mocktest${mockNum}</title>
<style>body{font-family:Arial;padding:32px;color:#222;max-width:860px;margin:0 auto}
.logo{font-size:22px;font-weight:900;color:#4f8ef7}
h1{color:#4f8ef7;font-size:18px;margin:8px 0 4px}
table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
th{background:linear-gradient(135deg,#4f8ef7,#a855f7);color:#fff;padding:10px 13px;text-align:left}
td{padding:9px 13px;border-bottom:1px solid #eee}
tr.gold td{background:rgba(251,191,36,0.1)!important}
tr.loser td{background:rgba(239,68,68,0.05)!important}
footer{margin-top:24px;color:#aaa;font-size:10px;text-align:center}
</style></head><body>
<div class="logo">⚡ Ranklify</div>
<p style="color:#888;font-size:11px">DDCET Group Mock Test</p>
<h1>Group Mock Test Result — #${mockNum}</h1>
<table style="width:auto;margin-bottom:12px;font-size:13px">
  <tr><td><b>Student</b></td><td style="padding-left:20px">${user?.name||"—"}</td></tr>
  <tr><td><b>Exam Type</b></td><td style="padding-left:20px">Group Mock Test</td></tr>
  <tr><td><b>Your Score</b></td><td style="padding-left:20px">${r.score}</td></tr>
  <tr><td><b>Your Rank</b></td><td style="padding-left:20px">${r.myRank||"—"}</td></tr>
  <tr><td><b>Date</b></td><td style="padding-left:20px">${r.date||new Date().toLocaleDateString("en-IN")}</td></tr>
</table>
${ranked.length>0?`<h2 style="font-size:15px;color:#444;margin-top:20px">Full Group Results</h2>
<table><thead><tr><th>Rank</th><th>Name</th><th>Score /200</th><th>Correct</th><th>Wrong</th><th>Accuracy</th></tr></thead>
<tbody>${ranked.map((p,i)=>`<tr class="${i===0?"gold":i===ranked.length-1?"loser":""}">
  <td><b>${rankLabels[i]||"#"+(i+1)}</b></td>
  <td><b>${p.name}</b>${p.name===user?.name?" (You)":""}</td>
  <td style="color:#4f8ef7;font-weight:800">${p.score}</td>
  <td style="color:#16a34a">${p.correct}</td>
  <td style="color:#dc2626">${p.wrong}</td>
  <td>${p.accuracy}%</td>
</tr>`).join("")}</tbody></table>`:""}
<footer>Generated by Ranklify · File: ranklify.mocktest${mockNum}.pdf</footer>
</body></html>`;
  triggerDownload(html, `ranklify.mocktest${mockNum}.pdf`);
}

function unitPDF(r, user) {
  const html=`<!DOCTYPE html><html><head><title>Ranklify Unit Test</title>
<style>body{font-family:Arial;padding:32px;color:#222;max-width:800px;margin:0 auto}
.logo{font-size:22px;font-weight:900;color:#4f8ef7}
h1{color:#4f8ef7;font-size:18px;margin:8px 0}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}
.box{background:#f3f4f6;border-radius:8px;padding:14px;text-align:center}
.bv{font-size:22px;font-weight:800;color:#4f8ef7}.bl{font-size:11px;color:#666;margin-top:4px}
footer{margin-top:24px;color:#aaa;font-size:10px;text-align:center}
</style></head><body>
<div class="logo">⚡ Ranklify</div>
<p style="color:#888;font-size:11px">DDCET Unit Test</p>
<h1>Unit Test: ${r.chapter||r.subject||"Chapter Test"}</h1>
<table style="font-size:13px;margin-bottom:12px">
  <tr><td><b>Student</b></td><td style="padding-left:20px">${user?.name||"—"}</td></tr>
  <tr><td><b>Chapter</b></td><td style="padding-left:20px">${r.chapter||r.subject||"—"}</td></tr>
  <tr><td><b>Date</b></td><td style="padding-left:20px">${r.date||"—"}</td></tr>
</table>
<div class="grid">
  <div class="box"><div class="bv">${r.score}</div><div class="bl">Score</div></div>
  <div class="box"><div class="bv">${r.correct}</div><div class="bl">Correct</div></div>
  <div class="box"><div class="bv">${r.wrong}</div><div class="bl">Wrong</div></div>
  <div class="box"><div class="bv">${r.unanswered||0}</div><div class="bl">Unattempted</div></div>
  <div class="box"><div class="bv">${r.accuracy}%</div><div class="bl">Accuracy</div></div>
</div>
<footer>Generated by Ranklify · Unit Test History</footer>
</body></html>`;
  triggerDownload(html, `ranklify.unittest.${(r.chapter||"test").replace(/\s+/g,"_")}.pdf`);
}

/* ═══════════════════════════════════════════════════════════ */
export default function History() {
  const { user, myResults, myUnitResults, users, darkMode } = useApp();
  const [tab, setTab] = useState("unit"); // unit | personal | group

  const T      = darkMode;
  const txt    = T ? "#e2e2f0" : "#111";
  const sub    = T ? "#555"    : "#888";
  const cardBg = T ? "rgba(255,255,255,0.03)" : "#fff";
  const cardBr = T ? "rgba(255,255,255,0.07)" : "#e5e7eb";

  /* personal mocks (not group) sorted newest first */
  const personalMocks = [...(myResults||[])]
    .filter(r => r.isMock && !r.isGroup)
    .sort((a,b) => (b.createdAt||0)-(a.createdAt||0));

  /* group mocks sorted newest first */
  const groupMocks = [...(myResults||[])]
    .filter(r => r.isMock && r.isGroup)
    .sort((a,b) => (b.createdAt||0)-(a.createdAt||0));

  /* unit tests sorted newest first */
  const unitTests = [...(myUnitResults||[])]
    .sort((a,b) => (b.createdAt||0)-(a.createdAt||0));

  /* sequential mock number across all mocks in order taken */
  const allMocks = [...(myResults||[])]
    .filter(r => r.isMock)
    .sort((a,b) => (a.createdAt||0)-(b.createdAt||0));
  const getMockNum = (id) => allMocks.findIndex(r=>r.id===id)+1;

  const TABS = [
    {id:"unit",     label:"📝 Unit Tests",    count:unitTests.length},
    {id:"personal", label:"🎯 Personal Mocks", count:personalMocks.length},
    {id:"group",    label:"👥 Group Mocks",    count:groupMocks.length},
  ];

  /* ── stat badge ── */
  function StatBadge({label, value, color}) {
    return (
      <div style={{background:`${color}11`,border:`1px solid ${color}22`,borderRadius:8,padding:"8px 14px",textAlign:"center",minWidth:70}}>
        <div style={{fontSize:18,fontWeight:900,color}}>{value}</div>
        <div style={{fontSize:10,color:sub,marginTop:2}}>{label}</div>
      </div>
    );
  }

  /* ── accuracy bar ── */
  function AccBar({pct}) {
    const c = pct>=70?"#4ade80":pct>=50?"#fbbf24":"#f87171";
    return (
      <div style={{flex:1,maxWidth:100}}>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}>
          <span style={{fontSize:10,color:sub}}>Accuracy</span>
          <span style={{fontSize:10,fontWeight:800,color:c}}>{pct}%</span>
        </div>
        <div style={{height:4,background:T?"rgba(255,255,255,0.06)":"#f0f0f0",borderRadius:2,overflow:"hidden"}}>
          <div style={{height:"100%",width:`${pct}%`,background:`linear-gradient(90deg,${c},${c}88)`,borderRadius:2}}/>
        </div>
      </div>
    );
  }

  /* empty state */
  function Empty({icon, msg}) {
    return (
      <div style={{textAlign:"center",padding:"60px 20px"}}>
        <div style={{fontSize:52,marginBottom:14}}>{icon}</div>
        <div style={{fontSize:16,fontWeight:800,color:txt,marginBottom:8}}>{msg}</div>
        <div style={{fontSize:13,color:sub}}>Your results will appear here after you take tests.</div>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:20}}>
        <div style={{width:44,height:44,borderRadius:12,background:"linear-gradient(135deg,#4f8ef7,#a855f7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>📋</div>
        <div>
          <div style={{fontSize:22,fontWeight:900,color:txt}}>History</div>
          <div style={{fontSize:12,color:sub}}>All your test results in one place</div>
        </div>
      </div>

      {/* Summary stats */}
      <div style={{display:"flex",gap:10,marginBottom:20,flexWrap:"wrap"}}>
        <StatBadge label="Unit Tests"    value={unitTests.length}    color="#a855f7"/>
        <StatBadge label="Solo Mocks"    value={personalMocks.length} color="#4f8ef7"/>
        <StatBadge label="Group Mocks"   value={groupMocks.length}    color="#22c55e"/>
        <StatBadge label="Total Tests"   value={(myResults?.length||0)+(myUnitResults?.length||0)} color="#fbbf24"/>
      </div>

      {/* Tabs */}
      <div style={{display:"flex",gap:8,marginBottom:20,flexWrap:"wrap"}}>
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)}
            style={{padding:"9px 18px",borderRadius:10,border:"none",cursor:"pointer",fontSize:13,fontWeight:700,fontFamily:"inherit",transition:"all 0.2s",
              background:tab===t.id?"linear-gradient(135deg,#4f8ef7,#a855f7)":T?"rgba(255,255,255,0.06)":"#f3f4f6",
              color:tab===t.id?"#fff":sub}}>
            {t.label} <span style={{opacity:0.7,fontSize:11}}>({t.count})</span>
          </button>
        ))}
      </div>

      {/* ══ TAB: UNIT TESTS ══════════════════════════════════ */}
      {tab==="unit" && (
        unitTests.length===0 ? <Empty icon="📝" msg="No unit tests yet"/> :
        <div style={{display:"flex",flexDirection:"column",gap:12}}>
          {unitTests.map((r,i) => (
            <div key={r.id} style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:14,padding:"18px 20px"}}>
              <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",flexWrap:"wrap",gap:12}}>
                <div style={{flex:1}}>
                  <div style={{fontWeight:900,fontSize:15,color:txt,marginBottom:4}}>{r.chapter||r.subject||"Chapter Test"}</div>
                  <div style={{fontSize:11,color:sub,marginBottom:12}}>{r.subject||""} · {r.date}</div>
                  <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>
                    <StatBadge label="Score"    value={r.score}           color="#4f8ef7"/>
                    <StatBadge label="Correct"  value={r.correct}         color="#4ade80"/>
                    <StatBadge label="Wrong"    value={r.wrong}           color="#f87171"/>
                    <StatBadge label="Accuracy" value={`${r.accuracy}%`}  color="#fbbf24"/>
                  </div>
                </div>
                <div style={{display:"flex",flexDirection:"column",gap:8,alignItems:"flex-end"}}>
                  <div style={{fontSize:28,fontWeight:900,color:r.accuracy>=70?"#4ade80":r.accuracy>=50?"#fbbf24":"#f87171"}}>{r.score}</div>
                  <div style={{fontSize:10,color:sub}}>marks</div>
                  <button onClick={() => unitPDF(r,user)}
                    style={{padding:"7px 16px",borderRadius:8,border:"none",cursor:"pointer",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",color:"#fff",fontSize:11,fontWeight:700,fontFamily:"inherit"}}>
                    ⬇ PDF
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ══ TAB: PERSONAL MOCKS ══════════════════════════════ */}
      {tab==="personal" && (
        personalMocks.length===0 ? <Empty icon="🎯" msg="No personal mock tests yet"/> :
        <div style={{display:"flex",flexDirection:"column",gap:12}}>
          {personalMocks.map((r,i) => {
            const mNum = getMockNum(r.id);
            return (
              <div key={r.id} style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:14,padding:"18px 20px"}}>
                <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",flexWrap:"wrap",gap:12}}>
                  <div style={{flex:1}}>
                    <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}>
                      <span style={{fontWeight:900,fontSize:15,color:txt}}>Mock Test #{mNum}</span>
                      <span style={{fontSize:10,padding:"2px 8px",borderRadius:20,background:"rgba(79,142,247,0.12)",color:"#7aadff",fontWeight:700}}>
                        {r.testType==="practice"?"Practice":"Full DDCET"}
                      </span>
                    </div>
                    <div style={{fontSize:11,color:sub,marginBottom:12}}>{r.date} · {r.questions||100} questions</div>
                    <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>
                      <StatBadge label="Score /200" value={r.score}           color="#4f8ef7"/>
                      <StatBadge label="Correct"    value={r.correct}         color="#4ade80"/>
                      <StatBadge label="Wrong"      value={r.wrong}           color="#f87171"/>
                      <StatBadge label="Accuracy"   value={`${r.accuracy}%`}  color="#22d3ee"/>
                      <StatBadge label="Time"       value={`${Math.floor((r.timeTaken||0)/60)}m`} color="#a855f7"/>
                    </div>
                  </div>
                  <div style={{display:"flex",flexDirection:"column",gap:8,alignItems:"flex-end"}}>
                    <div style={{fontSize:36,fontWeight:900,color:"#4f8ef7"}}>{r.score}</div>
                    <div style={{fontSize:10,color:sub}}>/200 marks</div>
                    <button onClick={() => personalPDF(r,user,mNum)}
                      style={{padding:"8px 16px",borderRadius:9,border:"none",cursor:"pointer",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",color:"#fff",fontSize:12,fontWeight:700,fontFamily:"inherit",whiteSpace:"nowrap"}}>
                      ⬇ ranklify.mocktest{mNum}.pdf
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ══ TAB: GROUP MOCKS ═════════════════════════════════ */}
      {tab==="group" && (
        groupMocks.length===0 ? <Empty icon="👥" msg="No group mock tests yet"/> :
        <div style={{display:"flex",flexDirection:"column",gap:12}}>
          {groupMocks.map((r,i) => {
            const mNum         = getMockNum(r.id);
            const participants = r.participants || [];
            const myRankNum    = r.myRank;
            const rankColor    = myRankNum===1?"#fbbf24":myRankNum===participants.length&&participants.length>1?"#f87171":"#4ade80";
            const rankLabel    = myRankNum===1?"🥇 1st":myRankNum===2?"🥈 2nd":myRankNum===3?"🥉 3rd":myRankNum===participants.length&&participants.length>1?"💔 Loser":`#${myRankNum}`;
            return (
              <div key={r.id} style={{background:cardBg,border:`1px solid ${cardBr}`,borderRadius:14,padding:"18px 20px"}}>
                <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",flexWrap:"wrap",gap:12}}>
                  <div style={{flex:1}}>
                    <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:4}}>
                      <span style={{fontWeight:900,fontSize:15,color:txt}}>Group Mock #{mNum}</span>
                      <span style={{fontSize:11,padding:"3px 10px",borderRadius:20,background:`${rankColor}15`,color:rankColor,fontWeight:800}}>
                        {rankLabel}
                      </span>
                    </div>
                    <div style={{fontSize:11,color:sub,marginBottom:12}}>
                      {r.date} · {participants.length||r.title?.match(/\d+/)?.[0]||"?"} players
                    </div>

                    {/* participants mini list */}
                    {participants.length > 0 && (
                      <div style={{display:"flex",flexDirection:"column",gap:4,marginBottom:12}}>
                        {[...participants].sort((a,b)=>b.score-a.score).map((p,pi) => {
                          const isMe = p.name===user?.name;
                          const pl   = ["🥇","🥈","🥉","💔"][pi]||`#${pi+1}`;
                          return (
                            <div key={pi} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 10px",borderRadius:8,background:isMe?T?"rgba(79,142,247,0.08)":"rgba(79,142,247,0.04)":"transparent"}}>
                              <span style={{fontSize:14}}>{pl}</span>
                              <span style={{fontSize:12,fontWeight:isMe?800:500,color:isMe?"#7aadff":txt,flex:1}}>{p.name}{isMe?" (You)":""}</span>
                              <span style={{fontSize:13,fontWeight:700,color:"#4f8ef7"}}>{p.score}</span>
                              <span style={{fontSize:11,color:sub}}>{p.accuracy}%</span>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>
                      <StatBadge label="Score /200" value={r.score}          color="#4f8ef7"/>
                      <StatBadge label="Correct"    value={r.correct}        color="#4ade80"/>
                      <StatBadge label="Wrong"      value={r.wrong}          color="#f87171"/>
                      <StatBadge label="Accuracy"   value={`${r.accuracy}%`} color="#22d3ee"/>
                    </div>
                  </div>
                  <div style={{display:"flex",flexDirection:"column",gap:8,alignItems:"flex-end"}}>
                    <div style={{fontSize:36,fontWeight:900,color:rankColor}}>{r.score}</div>
                    <div style={{fontSize:10,color:sub}}>/200 marks</div>
                    <button onClick={() => groupPDF(r,user,mNum)}
                      style={{padding:"8px 16px",borderRadius:9,border:"none",cursor:"pointer",background:"linear-gradient(135deg,#4f8ef7,#a855f7)",color:"#fff",fontSize:12,fontWeight:700,fontFamily:"inherit",whiteSpace:"nowrap"}}>
                      ⬇ ranklify.mocktest{mNum}.pdf
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
